#ifndef __GAMEWORLD_COREUSENAMEDEF_H__
#define __GAMEWORLD_COREUSENAMEDEF_H__

#define		MAX_PLAYER_IN_ACCOUNT			3


enum enumMSG_ID
{
	enumMSG_ID_NONE = 0,
	enumMSG_ID_TEAM_KICK_One,
	enumMSG_ID_TEAM_DISMISS,
	enumMSG_ID_TEAM_LEAVE,
	enumMSG_ID_TEAM_REFUSE_INVITE,
	enumMSG_ID_TEAM_REFUSE_APPLYJOIN,
	enumMSG_ID_TEAM_REFUSE_DISABLETEAM,
	enumMSG_ID_TEAM_REFUSE_SUMMON,
	enumMSG_ID_TEAM_CANNOT_ADDHIM,
	enumMSG_ID_TEAM_SELF_ADD,
	enumMSG_ID_TEAM_CHANGE_CAPTAIN_FAIL,
	enumMSG_ID_TEAM_CHANGE_CAPTAIN_FAIL2,
	enumMSG_ID_OBJ_CANNOT_PICKUP,
	enumMSG_ID_OBJ_TOO_FAR,
	enumMSG_ID_DEC_MONEY,
	enumMSG_ID_GET_ITEM,
	enumMSG_ID_TEAMATE_GET_ITEM,
	enumMSG_ID_MONEY_CANNOT_PICKUP,
	enumMSG_ID_CANNOT_ADD_TEAM,
	enumMSG_ID_TARGET_CANNOT_ADD_TEAM,
	enumMSG_ID_PK_REFUSE_EXERCISE,
	enumMSG_ID_PK_ACCETP_EXERCISE,
	enumMSG_ID_PK_READY_EXERCISE,
	enumMSG_ID_PK_EXERCISE_WIN,
	enumMSG_ID_PK_EXERCISE_LOSE,
	enumMSG_ID_PK_ERROR_1,
	enumMSG_ID_PK_ERROR_2,
	enumMSG_ID_PK_ERROR_3,
	enumMSG_ID_PK_ERROR_4,
	enumMSG_ID_PK_ERROR_5,
	enumMSG_ID_PK_ERROR_6,
	enumMSG_ID_PK_ERROR_7,
	enumMSG_ID_PK_ERROR_8,
	enumMSG_ID_PK_ERROR_9,
	enumMSG_ID_PK_ERROR_10,
	enumMSG_ID_PK_ERROR_11,
	enumMSG_ID_PK_ERROR_12,
	enumMSG_ID_PK_ERROR_13,
	enumMSG_ID_PK_ERROR_14,
	enumMSG_ID_PK_ERROR_15,
	enumMSG_ID_PK_ERROR_16,
	enumMSG_ID_PK_ERROR_17,
	enumMSG_ID_PK_ERROR_18,
	enumMSG_ID_PK_ERROR_19,
	enumMSG_ID_PK_ERROR_20,
	enumMSG_ID_PK_ERROR_21,
	enumMSG_ID_PK_ERROR_22,
	enumMSG_ID_PK_ERROR_23,
	enumMSG_ID_PK_ERROR_24,
	enumMSG_ID_DEATH_LOSE_ITEM,
	enumMSG_ID_TONG_REFUSE_ADD,
	enumMSG_ID_TONG_BE_KICK,
	enumMSG_ID_TONG_LEAVE_SUCCESS,
	enumMSG_ID_TONG_LEAVE_FAIL,
	enumMSG_ID_TONG_CHANGE_AS_MASTER,
	enumMSG_ID_TONG_CHANGE_AS_MEMBER,
	enumMSG_ID_TONG_DISMISS,
	enumMSG_ID_TEAM_ERROR01,
	enumMSG_ID_TEAM_ERROR02,
	enumMSG_ID_TEAM_ERROR03,
	enumMSG_ID_TEAM_ERROR04,
	enumMSG_ID_TEAM_ERROR05,
	enumMSG_ID_TONG_MONEY,
	enumMSG_ID_ITEM_USINGTIMES_END,
	enumMSG_ID_CANNOT_PK_WHEN_USEEXTBOX,		// 当把装备锁定之后，如果PK值大于3则无法再进行PK,以防止装备在死亡惩罚时丢失
	enumMSG_ID_CANNOT_MOVEORTRADE_ITEM,			// 禁止道具的移动与交易
	enumMSG_ID_PARTNER_DEATH_NOT_CALLOUT,		// 同伴死亡惩罚中不能被召唤
	enumMSG_ID_PARTNER_INTERVAL_NOT_CALLOUT,	// 同伴召唤间隔未到不能被召唤
	enumMSG_ID_PARTNER_FORBID_CALLOUT,			// 同伴禁止召唤状态
	enumMSG_ID_PARTNER_FORBID_REMOVE,			// 禁止解散同伴(箱子锁定)
	enumMSG_ID_PARTNER_FORBID_REMOVE2,			// 禁止解散同伴(最后一个)
	enumMSG_ID_BANTIME_CANNOT_ACCESS,			// 暂时禁止操作
	enumMSG_ID_PASSWORD_FAILED_TIMES,			// 密码的输错次数
	enumMSG_ID_LIFESKILL_FORBIDSTATE,
	enumMSG_ID_PEER_FORBITPLAYERTRADE,			// 对方现在不能进入交易状态
	enumMSG_ID_TRADE_SELF_ACCOUNT_LOCK	,		// 自己账号锁定不能交易
	enumMSG_ID_TRADE_TARGET_ACCOUNT_LOCK,		// 对方账号锁定不能交易
	enumMSG_ID_TRADE_COSUMEINFO,				// 在进行交易时消耗的非绑定与绑定物品的数量通知
	enumMSG_ID_NUM,
	
};

//---------------------------- 鼠标指针相关 ------------------------------
enum CURSOR_INDEX
{
	CURSOR_NORMAL = 0,
	CURSOR_POINT_TO_ATTACKABLE,	//移到攻击目标上
	CURSOR_POINT_TO_OBJ_NPC,	//移到一般OBJ或NPC上
	CURSOR_PICKABLE,			//可拾取
	CURSOR_SKILL_ENABLE,		//移到可使用增益技能的角色对象身上
	CURSOR_BUY,					//买东西
	CURSOR_SELL,				//卖东西
	CURSOR_REPAIR,				//修东西
	CURSOR_USE,                 //看对象的图标
	CURSOR_QUERY_STALL,			//看摊位
	CURSOR_STALL_MARK_PIRCE,	//为摆摊标价
	CURSOR_HAND,				//手
	CURSOR_FORGET,				//同伴遗忘技能
	CURSOR_HELP,				//帮助查询图标（属帮会分支，为方便合并加上）
	CURSOR_BIND,				//绑定物品
	CURSOR_UNBIND,				//解除绑定
	CURSOR_INDEX_COUNT,
};
#endif
