# Generated by vc2mak. (c) 2012 simon<senoutouya@gmail.com>.
# Project - onlinegamebase

# 缺省配置
ifndef CFG
	CFG=unify_debug
endif

# 编译器标记（若要做x86、x64的cross-compile请指定PLAT参数）
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
CFLAGS = -pthread $(PLAT)
LDFLAGS:=$(CFLAGS)
PLATLIBS += -lm -ldl -lrt $(PLATLIB)
endif

ifeq ($(UNAME), Solaris)
CFLAGS = -pthreads -I/usr/local/include $(PLAT)
LDFLAGS:=$(CFLAGS) -L/usr/local/lib
PLATLIBS += -lz -liconv -lm -lrt $(PLATLIB)
endif

ifeq ($(UNAME), FreeBSD)
CFLAGS = -pthread -I/usr/local/include $(PLAT)
LDFLAGS:=$(CFLAGS) -L/usr/local/lib
PLATLIBS += -lz -liconv -lm -lrt $(PLATLIB)
endif

CC=gcc
CXX=g++
CXXFLAGS=$(CFLAGS)
LD=$(CXX)
AR=ar
ARFLAGS=rcs

# 工程配置表
ifeq "$(CFG)" "unify_debug"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O0 -fexceptions -g -fstack-protector  -D_DEBUG  -I. -I../../include -I../../../LibQrt/Include -I../../../devenv/include -I/usr/include/mysql
	TARGET=../../lib/debug/libyol_libd.a
	VC_CONF_TYPE=typeStaticLibrary
endif

ifeq "$(CFG)" "unify_release"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O2 -fexceptions -g -fstack-protector  -DNDEBUG  -DKD_USE_JXEX_UNIFY -I. -I../../include -I../../../base/include -I../../../devenv/include -I/usr/include/mysql
	TARGET=../../lib/release/libonlinegamebase.a
	VC_CONF_TYPE=typeStaticLibrary
endif

.PHONY: all
all: $(TARGET)

ifndef TARGET
	@echo "无编译目标！unrecognized \$$CFG '$(CFG)'"
	@exit 1
endif

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cxx
	$(CXX) $(CXXFLAGS) -o $@ -c $<

YOL_LIB.VCPROJ= \
	./stdafx.h 

LUA_API= \
	./kfilescript.cpp \
	./klibscript.cpp 

SRC= \
	./iptransform.cpp \
	../../../sourcecode/include/onlinegamebase/iptransform.h \
	./kbadwordfilter.cpp \
	./kbadwordfilter.h \
	./kdatetimecontrol.cpp \
	./kdatetimecontrol.h \
	./keyes.cpp \
	../../include/onlinegamebase/keyes.h \
	../../../sourcecode/include/onlinegamebase/kguidhelper.h \
	./kjxexunify.cpp \
	../../../sourcecode/include/onlinegamebase/kjxexunify.h \
	./kluatimermgr.cpp \
	../../../sourcecode/include/onlinegamebase/kruntimedebug.h \
	./kruntimememleakdetect.cpp \
	./kscriptmanager.cpp \
	../../../sourcecode/include/onlinegamebase/kscriptmanager.h \
	../../../sourcecode/include/onlinegamebase/ksysservice.h \
	./ktimeline.cpp \
	../../../sourcecode/include/onlinegamebase/ktimeline.h \
	./ktimermgr.cpp \
	../../include/onlinegamebase/ktimermgr.h \
	./kunifyscript.cpp \
	./mysqldatabase.cpp \
	../../include/onlinegamebase/mysqldatabase.h \
	./performancestat.cpp \
	../../include/onlinegamebase/performancestat.h \
	./Regexp.cpp \
	./Regexp.h 

RAND= \
	./mersenne.cpp \
	./mother.cpp \
	../../include/onlinegamebase/rancombi.h \
	../../include/onlinegamebase/randomc.h \
	./userintf.cpp 

SRCS=$(YOL_LIB.VCPROJ) $(LUA_API) $(SRC) $(RAND) 

OBJS=$(patsubst %.cxx,%.o,$(patsubst %.cpp,%.o,$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(filter %.c %.cc %.cpp %.cxx,$(SRCS))))))

ifeq "$(VC_CONF_TYPE)" "typeStaticLibrary"
$(TARGET): $(OBJS)
	mkdir -p "$(dir $(TARGET))"
	$(AR) $(ARFLAGS) $@ $(OBJS)
endif

.PHONY: clean
clean:
	-rm -f $(OBJS) onlinegamebase.dep  ../../lib/debug/libyol_libd.a ../../lib/release/libonlinegamebase.a

.PHONY: depends
depends:
	-$(CXX) $(CXXFLAGS) -MM $(filter %.c %.cc %.cpp %.cxx,$(SRCS)) > onlinegamebase.dep

-include onlinegamebase.dep

