
Chat.BROADCAST_ID_EQUIP_GREEN = 1;
Chat.BROADCAST_ID_EQUIP_BLUE = 2;
Chat.BROADCAST_ID_EQUIP_PURPLE = 3;
Chat.BROADCAST_ID_EQUIP_ORANGE = 4;
Chat.BROADCAST_ID_EQUIP_RED = 5;
Chat.BROADCAST_ID_EQUIP_GOLD = 6;