/* -------------------------------------------------------------------------
//	文件名		：	luabuffereffect_table.hpp
//	创建者		：	LuaScriptTool
//	功能描述	：	本文件由VisualStudio宏生成，请不要手动修改！！
//	使用方法	：	在相应的CPP文件末端，include此文件
//
// -----------------------------------------------------------------------*/

DEFINE_LUA_CLASS_BEGIN(LuaCharacterBufferEffect)
	REGISTER_LUA_FUNC(DamageLifeV, "伤害生命值", "d", "伤害生命值数值;", "")
	REGISTER_LUA_FUNC(DamageLifeP, "伤害生命百分比", "d", "伤害生命值百分比值;", "")
	REGISTER_LUA_FUNC(DamageManaV, "伤害真气值", "d", "伤害真气值数值;", "")
	REGISTER_LUA_FUNC(DamageManaP, "伤害真气百分比", "d", "伤害真气值百分比值;", "")
	REGISTER_LUA_FUNC(Stun, "眩晕", "", "", "")
	REGISTER_LUA_FUNC(Fix, "定身", "", "", "")
	REGISTER_LUA_FUNC(Fear, "恐惧", "", "", "")
	REGISTER_LUA_FUNC(Silence, "沉默", "", "", "")
	REGISTER_LUA_FUNC(Crazy, "疯狂", "", "", "")
	REGISTER_LUA_FUNC(SlowP, "减低移动速度百分比", "d", "减速百分比数值;", "")
	REGISTER_LUA_FUNC(Knock, "击退", "ddddd", "击退距离;对方坐标x;对方坐标y;对方坐标z;对方方向;", "")
	REGISTER_LUA_FUNC(JumpTo, "跳跃到指定点", "dddddd", "起始点坐标x;起始点坐标y;起始点坐标z;目标点坐标x;目标点坐标y;目标点坐标z;", "")
	REGISTER_LUA_FUNC(AddCurLifeV, "增加当前生命值", "d", "增加生命值数值;", "")
	REGISTER_LUA_FUNC(AddCurLifeP, "增加当前生命百分比", "d", "增加生命百分比数值;", "")
	REGISTER_LUA_FUNC(AddCurManaV, "增加当前真气值", "d", "增加真气值数值;", "")
	REGISTER_LUA_FUNC(AddCurManaP, "增加当前真气百分比", "d", "增加真气百分比数值;", "")
	REGISTER_LUA_FUNC(AddCurPowerV, "增加当前集中值", "d", "增加集中值数值;", "")
	REGISTER_LUA_FUNC(AddCurPowerP, "增加当前集中值百分比", "d", "增加集中值百分比数值;", "")
	REGISTER_LUA_FUNC(DoDeath, "致死", "", "", "")
	REGISTER_LUA_FUNC(DoRevive, "复活", "dd", "复活后当前生命值占最大生命值的百分比;复活后当前真气/集中值占最大真气/集中值的百分比;", "")
	REGISTER_LUA_FUNC(GetCurrentBufferStack, "得到当前的buff层数", "d", "nBufTemplateId;", "")
	REGISTER_LUA_FUNC(ClearBuff, "清除对应ID的Buff", "d", "需要清除的Buff的ID;", "")
	REGISTER_LUA_FUNC(HasBuff, "判断玩家身上是否有对应模板id的buff", "d", "buff模板id;", "")
	REGISTER_LUA_FUNC(ClearCurrentBuff, "清除对应ID的Buff", "", "", "")
	REGISTER_LUA_FUNC(SetCurrentBuffer, "设置当前生效buffer", "", "", "")
	REGISTER_LUA_FUNC(ClearBuffByType, "清除特定类型的buff", "d", "需要清除的Buff的类型;", "")
	REGISTER_LUA_FUNC(ClearCD, "清除技能的冷却时间", "dd", "技能的Category类型，对应于Skill表;技能的Category值，对应于Skill表的对应Category列;", "")
	REGISTER_LUA_FUNC(PullTarget, "将目标拉到自己身边，拉回的速度固定，目标需要执行完拉回后才能执行其他指令", "ddddd", "击退距离;对方坐标x;对方坐标y;对方坐标z;对方方向;", "")
	REGISTER_LUA_FUNC(SetMapPos, "传送到目标地图的对应点", "ddd", "地图ID，对应于MapList之类的配置表;X轴偏移量;Y轴偏移量;", "")
	REGISTER_LUA_FUNC(Tp, "回门派", "d", "门派Id，1：无上轩辕；2：诛邪天曜；3：赤炼幽冥；4：魅影森罗;", "")
	REGISTER_LUA_FUNC(IgnorarmorV, "忽略目标护甲值", "d", "忽略护甲值数值;", "")
	REGISTER_LUA_FUNC(AddBuffTime, "添加对应Buff的持续时间", "ddd", "技能的Category类型，对应于Buff表;技能的Category值，对应于Buff表的对应Category列;增加的帧数数值;", "")
	REGISTER_LUA_FUNC(RefreshBuffTime, "刷新对应Buff的持续时间", "dd", "技能的Category类型，对应于Buff表;技能的Category值，对应于Buff表的对应Category列;", "")
	REGISTER_LUA_FUNC(ModifyDmgP, "更改造成的伤害百分比，为最终伤害", "ddd", "技能的Category类型，对应于Skill表，可填-1，意义为所有技能都增加;技能的Category值，对应于Skill表的对应Category列，当第一个参数为-1时无意义，当第一个参数不为-1时，该值可填-1;增加伤害的百分比数值;", "")
	REGISTER_LUA_FUNC(ModifyDmgV, "更改造成的伤害的值，为最终伤害", "ddd", "技能的Category类型，对应于Buff表;技能的Category值，对应于Buff表的对应Category列，当第一个参数为-1时无意义，当第一个参数不为-1时，该值可填-1;增加伤害的数值;", "")
	REGISTER_LUA_FUNC(AddConst, "增加体质", "d", "增加的体质的数值;", "")
	REGISTER_LUA_FUNC(AddStrth, "增加筋骨", "d", "增加筋骨的数值;", "")
	REGISTER_LUA_FUNC(AddAgile, "增加身法", "d", "增加身法的数值;", "")
	REGISTER_LUA_FUNC(AddIntel, "增加智力", "d", "增加智力的数值;", "")
	REGISTER_LUA_FUNC(AddSpirt, "增加精神", "d", "增加精神的数值;", "")
	REGISTER_LUA_FUNC(AddAllAttributeV, "增加全属性值", "d", "增加全属性的数值;", "")
	REGISTER_LUA_FUNC(AddAllAttributeP, "增加全属性百分比", "d", "增加百分比的数值;", "")
	REGISTER_LUA_FUNC(AddMaxLifeV, "按值增加生命上限值", "d", "增加的生命上限值数值;", "")
	REGISTER_LUA_FUNC(AddMaxLifeP, "按百分比增加生命上限值", "d", "增加的生命上限百分比数值;", "")
	REGISTER_LUA_FUNC(AddMaxManaV, "按值增加真气上限值", "d", "增加的真气上限值数值;", "")
	REGISTER_LUA_FUNC(AddMaxManaP, "按百分比增加真气上限值", "d", "增加的真气上限百分比数值;", "")
	REGISTER_LUA_FUNC(AddMaxPowerV, "按值增加集中值上限值", "d", "增加的集中值上限值数值;", "")
	REGISTER_LUA_FUNC(AddMaxPowerP, "按百分比增加集中值上限值", "d", "增加的集中值上限百分比数值;", "")
	REGISTER_LUA_FUNC(AddHitRateV, "增加命中值", "d", "增加命中值数值;", "")
	REGISTER_LUA_FUNC(AddCriticalRateV, "增加会心一击值", "d", "增加会心一击的数值;", "")
	REGISTER_LUA_FUNC(AddSkillCriticalRateV, "增加固定技能的会心一击值", "ddd", "技能的Category类型，对应于Skill表;技能的Category值，对应于Skill表的对应Category列，当第一个参数为-1时无意义，当第一个参数不为-1时，该值可填-1;增加的会心一击值的数值;", "")
	REGISTER_LUA_FUNC(AddCriticalDmgP, "增加会心一击伤害百分比", "d", "增加伤害的百分比;", "")
	REGISTER_LUA_FUNC(AddRunSpeedV, "增加移动速度", "d", "增加速度数值;", "")
	REGISTER_LUA_FUNC(AddArmorV, "增加护甲值", "d", "增加护甲的数值;", "")
	REGISTER_LUA_FUNC(AddDodgeV, "增加闪避值", "d", "增加闪避的数值;", "")
	REGISTER_LUA_FUNC(HideToNpc, "对npc隐身", "", "", "")
	REGISTER_LUA_FUNC(HideToPlayer, "对玩家隐身", "", "", "")
	REGISTER_LUA_FUNC(AddThreat, "增加仇恨值", "d", "增加的仇恨的数值;", "")
	REGISTER_LUA_FUNC(ReboundDmgP, "按比例反弹伤害", "d", "反弹伤害的百分比;", "")
	REGISTER_LUA_FUNC(ReboundDmgV, "按值反弹伤害", "d", "反弹伤害的数值;", "")
	REGISTER_LUA_FUNC(ReduceDmg, "按比例缩小伤害", "dd", "缩小伤害百分比;缩小的伤害最大值占生命上限的百分比，填-1为无上限;", "")
	REGISTER_LUA_FUNC(ReduceDmgByMana, "使用真气值抵挡伤害", "ddd", "抵挡伤害的百分比;每抵挡一点伤害需要消耗的真气值;抵挡伤害的上限占生命上限的百分比，填-1为无上限;", "")
	REGISTER_LUA_FUNC(TransDmgToLife, "造成的伤害转化为自身生命回复", "d", "伤害转化生命的百分比数值;", "")
	REGISTER_LUA_FUNC(TransDmgToMana, "造成的伤害转化为自身真气回复", "d", "伤害转化生命真气;", "")
	REGISTER_LUA_FUNC(ForceAttack, "强制Buff的接收者攻击Buff的发送者", "", "", "")
	REGISTER_LUA_FUNC(ChangeChannelType, "改变技能的引导类型", "dd", "技能的Category类型，对应于Skill表;技能的Category值，对应于Skill表的对应Category列，当第一个参数为-1时无意义，当第一个参数不为-1时，该值可填-1;", "")
	REGISTER_LUA_FUNC(ReduceChannelTime, "缩短引导时间", "ddd", "技能的Category类型，对应于Skill表，不可填-1;技能的Category值，对应于Skill表的对应Category列，该值可填-1;缩短的帧数;", "")
	REGISTER_LUA_FUNC(AddBuff, "给Buff的接收者添加Buff", "d", "添加的Buff的ID;", "")
	REGISTER_LUA_FUNC(AddBuffToSender, "给Buff的发送者添加Buff", "d", "添加的Buff的ID;", "")
	REGISTER_LUA_FUNC(KillSelf, "消除改魔法属性所属的Buff自身", "", "", "")
	REGISTER_LUA_FUNC(IgnorBuff, "免疫Buff，可成为被免疫Buff的接收者，但是该Buff的所有效果不会对该目标产生影响", "d", "免疫的Buff的ID(+:添加-:);", "")
	REGISTER_LUA_FUNC(IgnorBuffGroup, "免疫某一个Group的Buff效果，可成为被免疫Buff的接收者，但是该Buff的所有效果不会对该目标产生影响", "d", "免疫的Buff的Group的ID;", "")
	REGISTER_LUA_FUNC(IgnorBuffCate, "免疫某一个Cate的Buff效果，可成为被免疫Buff的接收者，但是该Buff的所有效果不会对该目标产生影响", "dd", "技能的Category类型，对应于Buff表，不可填-1;技能的Category值，对应于Buff表的对应Category列，该值可填-1;", "")
	REGISTER_LUA_FUNC(CastSkill, "释放技能，若为Out类条件，则由Buff的拥有者向事件的接收者释放，若为In类事件，则由Buff的拥有者向事件的发送者释放", "d", "释放的技能的ID;", "")
	REGISTER_LUA_FUNC(AddTreatLifeV, "增加治疗生命值", "d", "增加的数值;", "")
	REGISTER_LUA_FUNC(AddTreatLifeP, "增加治疗生命百分比", "d", "增加治疗生命的百分比数值，对应于Skill表的SkillMagnification列;", "")
	REGISTER_LUA_FUNC(AddTreatManaV, "增加治疗真气值", "d", "增加的数值;", "")
	REGISTER_LUA_FUNC(AddTreatManaP, "增加治疗真气百分比", "d", "增加治疗真气的百分比数值，对应于Skill表的SkillMagnification列;", "")
	REGISTER_LUA_FUNC(ReduceCostV, "按值减少释放技能的消耗", "ddd", "减少的数值;技能的Category类型，对应于Skill表，可填-1;技能的Category值，对应于Buff表的对应Category列，前一个参数填-1时，该值无意义，前一个参数不为-1时，该值可填-1;", "")
	REGISTER_LUA_FUNC(ReduceCostP, "按百分比减少释放技能的消耗", "ddd", "减少的百分比;技能的Category类型，对应于Skill表，可填-1;技能的Category值，对应于Buff表的对应Category列，前一个参数填-1时，该值无意义，前一个参数不为-1时，该值可填-1;", "")
	REGISTER_LUA_FUNC(IgnorDmg, "免疫伤害，所有可能令Buff拥有者造成生命值减少的效果均不生效", "", "", "")
	REGISTER_LUA_FUNC(AddExtSkillBuff, "给某一类技能添加一个Buff", "ddd", "技能的Category类型，对应于Skill表，可填-1;技能的Category值，对应于Buff表的对应Category列，前一个参数填-1时，该值无意义，前一个参数不为-1时，该值可填-1;增加的Buff的ID;", "")
	REGISTER_LUA_FUNC(DelExtSkillBuff, "删除某一类技能的一个Buff", "ddd", "技能的Category类型，对应于Skill表，可填-1;技能的Category值，对应于Buff表的对应Category列，前一个参数填-1时，该值无意义，前一个参数不为-1时，该值可填-1;删除的Buff的ID;", "")
	REGISTER_LUA_FUNC(AddMagnification, "增加某一类技能的攻击力百分比", "ddd", "技能的Category类型，对应于Skill表，可填-1;技能的Category值，对应于Buff表的对应Category列，前一个参数填-1时，该值无意义，前一个参数不为-1时，该值可填-1;增加的百分比数值，正数为增加，负数为减少;", "")
	REGISTER_LUA_FUNC(AddWeaponDmgP, "按百分比增加武器攻击力", "d", "增加的百分比数值;", "")
	REGISTER_LUA_FUNC(GetCurrProcBuffFightInfo, "獲得目前buff的nSkillId,nMagnification,nGrow,nIfUseSkillLv, nK", "[d]", "nBufferTemplateId;", "")
	REGISTER_LUA_FUNC(ResetBufferTime, "重置Buffer时间", "ddd", "技能nCateType;技能nCateId;修改值;", "")
	REGISTER_LUA_FUNC(RefreshBufferTime, "重置Buffer时间为原时间", "dd", "技能nCateType;技能nCateId;", "")
	REGISTER_LUA_FUNC(AppendData, "给玩家身上Buff添加附加数据", "ddd", "buff模板id;附加数据类型;附加数据值;", "")
	REGISTER_LUA_FUNC(GetAppendData, "给玩家身上Buff添加附加数据", "d", "附加数据类型;", "")
	REGISTER_LUA_FUNC(GetDestPosition, "得到玩家身上buff设置的目标点", "d", "buff模板id;", "")
	REGISTER_LUA_FUNC(SetTransParam, "设置转换属性数据", "ddd", "转换的原属性;要转换的属性;转换百分比;", "")
	REGISTER_LUA_FUNC(GetTransParam, "得到一个属性的关联属性", "d", "原属性;", "")

#ifdef GAME_SERVER
	REGISTER_LUA_FUNC(GetGroundBuffPosition, "得到地面buffer位置", "", "", "")
#endif // #ifdef GAME_SERVER
DEFINE_LUA_CLASS_END()
