# Generated by vc2mak. (c) 2012 simon<senoutouya@gmail.com>.
# Project - chat_gc

# 缺省配置
ifndef CFG
	CFG=debug
endif

# 编译器标记（若要做x86、x64的cross-compile请指定PLAT参数）
CC=gcc
CFLAGS=-pthread $(PLAT)
CXX=g++
CXXFLAGS=$(CFLAGS)
LD=$(CXX)
LDFLAGS:=$(CFLAGS)
AR=ar
ARFLAGS=rcs

# 工程配置表
ifeq "$(CFG)" "debug"
	CFLAGS+= -pipe -fpic -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O0 -fexceptions -g -fstack-protector  -DGAME_CENTER -DGCMOUDLE_EXPORTS -I. -I../../include -I../../include/serverbase -I../../../LibQrt/Include -I../../../devenv/include
	LDFLAGS+= -L../../../LibQrt/Lib/Win32 -L../../../devenv/lib/debug -L../../lib/debug -shared -shared-libgcc
	LIBS=-Wl,-rpath,'$$ORIGIN' -Wl,--start-group -lonlinegamebased -lcored -lmysqlclient -Wl,--end-group -lm -ldl -lrt
	TARGET=../../product/debug/gamecenter/libchat_gc.so
	VC_CONF_TYPE=typeDynamicLibrary
endif

ifeq "$(CFG)" "release"
	CFLAGS+= -pipe -fpic -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O2 -fexceptions -g -fstack-protector  -DKD_OP_GAME_CENTER -DGCMOUDLE_EXPORTS -I. -I../../include -I../../include/serverbase -I../../../base/include -I../../../devenv/include
	LDFLAGS+= -L../../../base/lib/release/linuxso -L../../../base/lib/release -L../../../devenv/lib/release -L../../lib/release -shared -shared-libgcc
	LIBS=-Wl,-rpath,'$$ORIGIN' -Wl,--start-group -lonlinegamebase -ldevbase -lcommon -lengine -lmysqlclient -Wl,--end-group -lm -ldl -lrt
	TARGET=../../product/release/gamecenter/libchat_gc.so
	VC_CONF_TYPE=typeDynamicLibrary
endif

.PHONY: all
all: $(TARGET)

ifndef TARGET
	@echo "无编译目标！unrecognized \$$CFG '$(CFG)'"
	@exit 1
endif

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cxx
	$(CXX) $(CXXFLAGS) -o $@ -c $<

CHAT_GC.VCPROJ= \
	./chat/stdafx.h 

协议= \
	../../../sourcecode/include/gcmodule/chat/kchatchannelptc.h \
	./chat/kchatprotocolprocess_gc.cpp \
	./chat/kchatprotocolprocess_gc.h 

机制= \
	../../../sourcecode/include/gcmodule/chat/kchanneldef.h \
	./chat/kchatapply_gc.cpp \
	./chat/kchatapply_gc.h \
	../../../sourcecode/include/gcmodule/chat/kchatchannel.h 

模块= \
	./chat/kchatmodule_gc.cpp \
	./chat/kchatmodule_gc.h 

SRCS=$(CHAT_GC.VCPROJ) $(协议) $(机制) $(模块) 

OBJS=$(patsubst %.cxx,%.o,$(patsubst %.cpp,%.o,$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(filter %.c %.cc %.cpp %.cxx,$(SRCS))))))

ifeq "$(VC_CONF_TYPE)" "typeDynamicLibrary"
$(TARGET): $(OBJS)
	mkdir -p "$(dir $(TARGET))"
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
endif

.PHONY: clean
clean:
	-rm -f $(OBJS) chat_gc.dep  ../../product/debug/gamecenter/libchat_gc.so ../../product/release/gamecenter/libchat_gc.so

.PHONY: depends
depends:
	-$(CXX) $(CXXFLAGS) -MM $(filter %.c %.cc %.cpp %.cxx,$(SRCS)) > chat_gc.dep

-include chat_gc.dep

