/* -------------------------------------------------------------------------
//	文件名		：	kluaplayer_table.hpp
//	创建者		：	LuaScriptTool
//	功能描述	：	本文件由VisualStudio宏生成，请不要手动修改！！
//	使用方法	：	在相应的CPP文件末端，include此文件
//
// -----------------------------------------------------------------------*/

DEFINE_LUA_CLASS_BEGIN(KLuaPlayer)
	REGISTER_LUA_DWORD_READONLY(Id, "")
	REGISTER_LUA_FUNC(SetPosition, "设置逻辑坐标(瞬移应该调用TeleportTo，这个只准调试用，否则会造成同步问题)", "ddd", "x;y;z;", "")
	REGISTER_LUA_FUNC(SysMsg, "向玩家发送一系统消息", "s", "消息内容;", "")
	REGISTER_LUA_FUNC(IsBZonePlayer, "是否是跨服过来的玩家", "", "", "")
	REGISTER_LUA_FUNC(IsCaptain, "是否为队长", "", "", "1:是， 0：不是")
	REGISTER_LUA_FUNC(GetKinId, "获取家族Id", "", "", "返回家族Id")
	REGISTER_LUA_FUNC(GetKinMasterId, "获取家族族长Id", "", "", "返回家族族长Id")
	REGISTER_LUA_FUNC(IsKinMaster, "是否本家族族长", "", "", "返回0和1")
	REGISTER_LUA_FUNC(GetGameState, "获取玩家状态", "", "", "")
	REGISTER_LUA_FUNC(GetTeamId, "得到队伍ID", "", "", "返回队伍ID")
	REGISTER_LUA_FUNC(GetSysTeamId, "得到系统队伍ID", "", "", "返回系统队伍ID")
	REGISTER_LUA_FUNC(SetTeamId, "设置队伍Id", "dd", "bSystem，由gc传过来;nTeamId，由gc传过来;", "")
	REGISTER_LUA_FUNC(OnPayFinsh, "支付完成给奖励", "dd", "nType，由gc传过来 1或者2;nCoin，由gc传过来充值的金额;", "")

#ifdef GAME_SERVER
	REGISTER_LUA_FUNC(TeleportTo, "瞬移(传送)", "dddd[dd]", "MapId;x;y;z;bOnThisGs(是否在本服加载地图);nMapIndex;", "")
	REGISTER_LUA_FUNC(SetPositionForSaving, "设置保存位置", "dddd", "MapId;x;y;z;", "")
	REGISTER_LUA_FUNC(BattleZoneTransfer, "传送到战场服务器", "[ddd]", "nPosX;nPosY;nPosZ;", "")
	REGISTER_LUA_FUNC(DoMultiTransferRequest, "多人副本跨服传送", "", "", "")
	REGISTER_LUA_FUNC(DoGetMultiAwardRequest, "跨服回来后请求奖励信息", "", "", "")
	REGISTER_LUA_FUNC(DoGetCrossSvExDataRequest, "跨服回来后请求额外数据", "", "", "")
	REGISTER_LUA_FUNC(BattleZoneReturn, "从战场传送回原服务器", "[dddd]", "nMapId;nPosX;nPosY;nPosZ;", "")
	REGISTER_LUA_FUNC(ReturnToLastServer, "传送回原服务器", "[d]", "nExValue;", "")
	REGISTER_LUA_STRING_READONLY(Account, "玩家账户")
	REGISTER_LUA_STRING_READONLY(LoginIp, "玩家此次登陆IP")
	REGISTER_LUA_FUNC(CallClientScript, "远程调用客户端脚本", "{s}", "szCall:要调用的函数。随后跟着调用参数。;", "发送成功：1，发送失败：nil")
	REGISTER_LUA_FUNC(SendDialog, "发送Npc对话框", "s", "对话内容及选项;", "")
	REGISTER_LUA_FUNC(SendTalk, "发送剧情对话", "s", "对话内容;", "")
	REGISTER_LUA_FUNC(SendBlackMsg, "发送黑条字幕", "s", "字幕内容;", "")
	REGISTER_LUA_FUNC(SyncDegree, "发送次数", "sdd", "模块名称;当前次数;最大次数;", "")
	REGISTER_LUA_FUNC(SendNoticeMsg, "发送公告字幕", "s", "字幕内容;", "")
	REGISTER_LUA_FUNC(KickOut, "踢玩家下线，需指明原因", "", "", "")
	REGISTER_LUA_FUNC(ReturnToLastCity, "传回城市（最近去过的非副本场景）", "", "", "")
	REGISTER_LUA_FUNC(GetLastSaveCity, "得到最近去过的城市非副本场景", "", "", "")
	REGISTER_LUA_FUNC(IsGm, "是否GM（测试功能）", "", "", "")
	REGISTER_LUA_FUNC(InviteJoinTeam, "邀请玩家加入队伍", "ds", "nPlayerID:  玩家id;pszName:  玩家名字;", "1 发送成功")
	REGISTER_LUA_FUNC(LeaveTeam, "离开队伍", "", "", "1 发送成功")
	REGISTER_LUA_FUNC(GetLastSaveTime, "get last save time", "", "", "")
	REGISTER_LUA_FUNC(GetAccountCoin, "Get Account Coin", "", "", "")
	REGISTER_LUA_FUNC(GetLimitPlayTimeFlag, "防沉迷标志位", "", "", "")
	REGISTER_LUA_FUNC(GetLimitOnlineSecond, "防沉迷累计在线时间", "", "", "")
	REGISTER_LUA_FUNC(GetLimitOfflineSecond, "防沉迷累计离线时间", "", "", "")
	REGISTER_LUA_FUNC(GetAwardFlag, "获取防沉迷状态下收益标志", "", "", "")
	REGISTER_LUA_FUNC(SetAwardFlag, "设置防沉迷状态下收益标志", "d", "收益标志;", "")
	REGISTER_LUA_FUNC(CancelProgressBar, "关闭进度条", "", "", "")
	REGISTER_LUA_FUNC(StartProgressBar, "开启一个进度条", "d", "间隔逻辑帧;", "--")
	REGISTER_LUA_FUNC(ClientShowHeadText, "客户端冒头顶文字", "", "", "")
	REGISTER_LUA_FUNC(IsSwim, "是否在泡澡（测试功能）", "", "", "")
	REGISTER_LUA_FUNC(ResetMeditationData, "重置玩家打坐数据", "", "", "")
	REGISTER_LUA_FUNC(SetTakeMeditationOfflineAwardTime, "设置玩家领取离线打坐经验时间", "", "", "")
	REGISTER_LUA_FUNC(GetTakeMeditationOfflineAwardTime, "获取玩家领取离线打坐经验时间", "", "", "")
	REGISTER_LUA_FUNC(GetLastMeditationOnlineTime, "获取玩家昨日打坐时间", "", "", "")
	REGISTER_LUA_FUNC(GetMeditationOnlineTime, "获取玩家今日在线打坐时间", "", "", "")
	REGISTER_LUA_FUNC(SetTrapInvalid, "设置trap点无效", "d", "trap点模板id;", "")
	REGISTER_LUA_FUNC(RemoveTrapInvalid, "", "d", "trap点模板id;", "")
	REGISTER_LUA_FUNC(IsTrapInvalid, "查看trap点是否失效", "d", "trap点模板id;", "")
	REGISTER_LUA_FUNC(GetBladeInfo, "获取大神附加属性", "", "", "{ nLife, nMana, nAttack，nDef，nHit，nMiss，nCrit，nResist }，失败返回nil")
#endif // #ifdef GAME_SERVER
DEFINE_LUA_CLASS_END()
