# Generated by vc2mak. (c) 2012 simon<senoutouya@gmail.com>.
# Project - roleserver

# 缺省配置
ifndef CFG
	CFG=debug
endif

# 编译器标记（若要做x86、x64的cross-compile请指定PLAT参数）
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
CFLAGS = -pthread $(PLAT)
LDFLAGS:=$(CFLAGS)
PLATLIBS += -lm -ldl -lrt $(PLATLIB)
endif

ifeq ($(UNAME), Solaris)
CFLAGS = -pthreads -I/usr/local/include $(PLAT)
LDFLAGS:=$(CFLAGS) -L/usr/local/lib
PLATLIBS += -lz -liconv -lm -lrt $(PLATLIB)
endif

ifeq ($(UNAME), FreeBSD)
CFLAGS = -pthread -I/usr/local/include $(PLAT)
LDFLAGS:=$(CFLAGS) -L/usr/local/lib
PLATLIBS += -lz -liconv -lm -lrt $(PLATLIB)
endif

CC=gcc
CXX=g++
CXXFLAGS=$(CFLAGS)
LD=$(CXX)
AR=ar
ARFLAGS=rcs

# 工程配置表
ifeq "$(CFG)" "debug"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O0 -fexceptions -g -fstack-protector  -D_DEBUG  -I. -I../../include -I../../include/serverbase -I../../../LibQrt/Include -I../../../devenv/include
	LDFLAGS+= -L../../lib/debug -L../../../LibQrt/Lib/Win32 -L../../../devenv/lib/debug
	LIBS=-Wl,-rpath,'$$ORIGIN' -Wl,--start-group -lQMysqlD -lcored -lmysqlclient  -Wl,--end-group $(PLATLIBS)
	TARGET=../../product/debug/roleserver/roleserverd.elf
	VC_CONF_TYPE=typeApplication
endif

ifeq "$(CFG)" "release"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O2 -fexceptions -g -fstack-protector  -DNDEBUG  -I. -I../../include -I../../include/serverbase -I../../../base/include -I../../../devenv/include
	LDFLAGS+= -L../../lib/release -L../../../base/lib/release -L../../../devenv/lib/release
	LIBS=-Wl,-rpath,'$$ORIGIN' -Wl,--start-group -ldevbase -lkgd_local -lengine -lcommon -lmysqlclient  -Wl,--end-group $(PLATLIBS)
	TARGET=../../product/release/roleserver/roleserver.elf
	VC_CONF_TYPE=typeApplication
endif

.PHONY: all
all: $(TARGET)

ifndef TARGET
	@echo "无编译目标！unrecognized \$$CFG '$(CFG)'"
	@exit 1
endif

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cxx
	$(CXX) $(CXXFLAGS) -o $@ -c $<

ROLESERVER.VCPROJ= \
	./resource.h \
	./roleserver.rc 

NETWORK= \
	./kroleservereyes.cpp \
	./kroleservereyes.h \
	./ksocketinterface.h \
	./ksocketlistener.cpp \
	./ksocketlistener.h 

APPFRAMEWORK= \
	./roleserver.cpp \
	./roleserver_utils.cpp \
	./stdafx.h 

DEFINITION= \
	./ikdbworker.h \
	./roledb_def.h \
	./roleserver_cfg.h \
	../../include/serverbase/protocol/roleserver_protocol.h 

DATABASE= \
	./kdbclusterworker.cpp \
	./kdbclusterworker.h \
	./kg_database.cpp \
	./kg_database.h \
	./kg_nameserver.cpp \
	./kg_nameserver.h 

LOGIC= \
	./kaccountindexing.cpp \
	./kaccountindexing.h \
	./kdbclustermanager.cpp \
	./kdbclustermanager.h \
	./kgatewayprocess.cpp \
	./kgatewayprocess.h \
	./kroleserver.cpp \
	./kroleserver.h \
	./kworker.cpp 

SRCS=$(ROLESERVER.VCPROJ) $(NETWORK) $(APPFRAMEWORK) $(DEFINITION) $(DATABASE) $(LOGIC) 

OBJS=$(patsubst %.cxx,%.o,$(patsubst %.cpp,%.o,$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(filter %.c %.cc %.cpp %.cxx,$(SRCS))))))

ifeq "$(VC_CONF_TYPE)" "typeApplication"
$(TARGET): $(OBJS)
	mkdir -p "$(dir $(TARGET))"
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
endif

.PHONY: clean
clean:
	-rm -f $(OBJS) roleserver.dep  ../../product/debug/roleserver/roleserverd.elf ../../product/release/roleserver/roleserver.elf

.PHONY: depends
depends:
	-$(CXX) $(CXXFLAGS) -MM $(filter %.c %.cc %.cpp %.cxx,$(SRCS)) > roleserver.dep

-include roleserver.dep

