
#pragma once

#include <vector>

// -------------------------------------------------------------------------
// 此枚举保存了所有对象的事件类型
// Warring:liuchang 服务端的前面加S比如emsKOBJXXXEVENT，客户端的加C比如emcKOBJXXXEVENT，两边都有的不用加比如emKOBJXXX
// Warring:定义事件,必须同时修改脚本定义:\\script\\event\\event.lua 
enum KE_OBJEVENT_TYPE
{
	emKOBJEVENTTYPE_NONE,

	// ---------------------------------------------------------------------
	// GameWorld 事件
	emKOBJEVENTTYPE_GAMEWORLD_BEGIN								= 0x00000000,
	emKOBJEVENTTYPE_GAMEWORLD_ADD_PLAYER,
	emKOBJEVENTTYPE_GAMEWORLD_ADD_NPC,
	emKOBJEVENTTYPE_GAMEWORLD_ADD_DOODAD,
	emKOBJEVENTTYPE_GAMEWORLD_REMOVE_PLAYER,
	emKOBJEVENTTYPE_GAMEWORLD_REMOVE_NPC,
	emKOBJEVENTTYPE_GAMEWORLD_REMOVE_DOODAD,
	emKOBJEVENTTYPE_GAMEWORLD_UNLOAD_SCENE,
	emKOBJEVENTTYPE_GAMEWORLD_LOST_CONNECT,						// 与服务器连接丢失
	emKOBJEVENTTYPE_GAMEWORLD_SHUTDOWN,							// 断开连接
	emKOBJEVENTTYPE_GC_CLIENT_MODULE_READY,						// 暂时放这里
	emKOBJEVENTTYPE_GAMEWORLD_SOCIETY_RANK_CHG,					// 社会发展水平改变
	emKOBJEVENTTYPE_GAMECENTER_LOST,									// 与gc模块的连接已断开
	emKOBJEVENTTYPE_GAMECENTER_CONNECT,									// 已连接到gc模块

	// ---------------------------------------------------------------------
	// Character 事件
	emKOBJEVENTTYPE_CHARACTER_BEGIN								= 0x00010000,
	emKOBJEVENTTYPE_CHARACTER_BEGIN_CAST_SKILL,					// 开始释放技能
	emKOBJEVENTTYPE_CHARACTER_END_CAST_SKILL,					// 结束释放技能
	emKOBJEVENTTYPE_CHARACTER_DODGE,							// 闪避技能事件
	emKOBJEVENTTYPE_CHARACTER_HIT,								// 命中事件
	emKOBJEVENTTYPE_CHARACTER_REACH_TARGET,						//  移动中到达目标
	emKOBJEVENTTYPE_CHARACTER_DETOUR_BEGIN,						// 移动中绕路开始
	emKOBJEVENTTYPE_CHARACTER_MOVE_DETOUR,						// 移动中绕路
	emKOBJEVENTTYPE_CHARACTER_DETOUR_END,						// 移动中绕路结束
	emKOBJEVENTTYPE_CHARACTER_MOVE_STOP,						//  停止移动
	emKOBJEVENTTYPE_CHARACTER_ROUND_OVER,						// 结束一个回合
	emKOBJEVENTTYPE_CHARACTER_ATTRIBUTE_CHANGED,				// 属性改变了
	emKOBJEVENTTYPE_CHARACTER_UPDATE_ALL_ATTRIBUTE,				// 更新所有属性
	emKOBJEVENTTYPE_CHARACTER_SET_DOING,						// 
	emKOBJEVENTTYPE_CHARACTER_KILL,								// 杀死了某人
	emKOBJEVENTTYPE_CHARACTER_DEATH,							// 死亡事件
	emKOBJEVENTTYPE_CHARACTER_ADDBUFFER,						// 添加一个Buffer
	emKOBJEVENTTYPE_CHARACTER_REMOVEBUFFER,						// 删除一个Buffer
	emKOBJEVENTTYPE_CHARACTER_REVIVE,							// 某人复活了
	emKOBJEVENTTYPE_CHARACTER_EXIT_COMBAT,						// character离开战场
	emKOBJEVENTTYPE_CHARACTER_ENTER_EXPSCENE,					// 进入移动地图
	emKOBJEVENTTYPE_CHARACTER_BEHIT,	                        // 被命中事件
	emKOBJEVENTTYPE_CHARACTER_BEDODGE,							// 被闪避技能事件
	emKOBJEVENTTYPE_CHARACTER_BEHITEDBYWIND,                    // 受到风属性攻击
	emKOBJEVENTTYPE_CHARACTER_BEHITEDBYTHUNDER,			        // 受到雷属性攻击
	emKOBJEVENTTYPE_CHARACTER_BEHITEDBYWATER,                   // 受到水属性攻击
	emKOBJEVENTTYPE_CHARACTER_BEHITEDBYFIRE,                    // 受到火属性攻击
	emKOBJEVENTTYPE_CHARACTER_SELFNODYING,                      // 自己生命高于20%
	emKOBJEVENTTYPE_CHARACTER_SELFDYING,                        // 自己生命不高于20%
	emKOBJEVENTTYPE_CHARACTER_SELFHEALTH,                       // 自身满血
	emKOBJEVENTTYPE_CHARACTER_SELFHURT,                         // 自身不满血
	emKOBJEVENTTYPE_CHARACTER_ENEMYDYING,                       // 敌方生命值不高于20%
	emKOBJEVENTTYPE_CHARACTER_SELFOUTOFMANA,                    // 自身魔法值不高于20点
	emKOBJEVENTTYPE_CHARACTER_SELFINMANA,                       // 自身魔法值高于20点
	emKOBJEVENTTYPE_CHARACTER_SELFBUFFERBECLEANED,              // 自己buffer被驱散
	emKOBJEVENTTYPE_CHARACTER_ENTER_COMBAT,						// character进入战场
	emKOBJEVENTTYPE_CHARACTER_PLAYSFX,                          // 播放特效
	emKOBJEVENTTYPE_CHARACTER_EFFECTRECEIVERLIST,               // 技能作用npc列表
	emKOBJEVENTTYPE_CHARACTER_NPCRELATION_CHANGED,              // npc关系改变
	emKOBJEVENTTYPE_CHARACTER_REBOUND,                          // 反击事件
	emKOBJEVENTTYPE_CHARACTER_FIERCE,                           // npc狂暴事件
	emKOBJEVENTTYPE_CHARACTER_MOVE,								// 角色移动
	emKOBJEVENTTYPE_CHARACTER_ENTER_TRAP,					// 进入trap
	emKOBJEVENTTYPE_CHARACTER_LEAVE_TRAP,						// 离开trap
	emKOBJEVENTTYPE_CHARACTER_START_AUTOPATH,					//开始寻路
	emKOBJEVENTTYPE_CHARACTER_END_AUTOPATH,						//中断寻路
	emKOBJEVENTTYPE_CHARACTER_FINISH_AUTOPATH,					//完成寻路
	emKOBJEVENTTYPE_CHARACTER_DAMAGE,                           //受伤事件
	emKOBJEVENTTYPE_CHARACTER_BOSS_BLOOD_CHANGED,               //boss血量改变事件
	emKOBJEVENTTYPE_CHARACTER_BORN,								//NPC出生事件
	emKOBJEVENTTYPE_CHARACTER_BUFFER_NOT_HIT,                   //buffer未命中
	emKOBJEVENTTYPE_CHARACTER_BUFFER_IMMUNITY,                  //buffer免疫
	emKOBJEVENTTYPE_CHARACTER_BUFFER_HIT,                       //buffer命中
	emKOBJEVENTTYPE_CHARACTER_LIFE_LESS_THAN,                   //生命少于
	emKOBJEVENTTYPE_CHARACTER_MANA_LESS_THAN,                   //mana少于
	emKOBJEVENTTYPE_CHARACTER_KNOCK,							// 被击退
	emKOBJEVENTTYPE_CHARACTER_PULL,								// 被拉拽
	emKOBJEVENTTYPE_CHARACTER_LEAVE_SCENE,						// 离开场景
	emKOBJEVENTTYPE_CHARACTER_ENTER_SCENE,						// 进入场景
	emKOBJEVENTTYPE_OFFLINE_FIGHT_EXIT,                         // 离线战斗结束

	emKOBJEVENTTYPE_CHARACTER_VIP_LEVEL,						//vip升级
	emKOBJEVENTTYPE_CHARACTER_TITLE_CARRY_1,					//携带的称号1
	emKOBJEVENTTYPE_CHARACTER_TITLE_CARRY_2,					//携带的称号2
	emKOBJEVENTTYPE_CHARACTER_TITLE_CARRY_3,					//携带的称号3

	// ---------------------------------------------------------------------
	// Player 事件
	emKOBJEVENTTYPE_PLAYER_BEGIN								= 0x00020000,
	emKOBJEVENTTYPE_PLAYER_PK_EXERCISE_INVITE,
	emKOBJEVENTTYPE_PLAYER_TEAM_RECEIVE_INVITE,
	emKOBJEVENTTYPE_PLAYER_TEAM_APPLY_ADD,
	emKOBJEVENTTYPE_PLAYER_LOGIN,								// 某人上线了
	emKOBJEVENTTYPE_PLAYER_LOGOUT,								// 某人下线了
	emKOBJEVENTTYPE_PLAYER_MSG_ARRIVE,							// 消息到达
	emKOBJEVENTTYPE_PLAYER_CAST_NIRVANA,                        // 玩家释放必杀技能
	emKOBJEVENTTYPE_PLAYER_TELEPORT,							// 某人执行了传送
	emKOBJEVENTTYPE_PLAYER_OPEN_DOODAD,							// 某人打开了doodad
	emKOBJEVENTTYPE_PLAYER_ITEM_OPS,							// 道具操作
	emKOBJEVENTTYPE_PLAYER_EQUIP_OPS,							// 装备操作


	// ---------------------------------------------------------------------
	// 场景事件
	emKOBJEVENTTYPE_SCENE_BEGIN									= 0x00030000,
	emKOBJEVENTTYPE_SCENE_CREATE,														// 创建场景
	emKOBJEVENTTYPE_SCENE_DELETE,														// 删除场景
	emKOBJEVENTTYPE_SCENE_RECYCLE,														// 副本回收
	emKOBJEVENTTYPE_SCENE_LOAD_FINISH,                                                  // 场景加载完成

	// ---------------------------------------------------------------------
	// Doodad事件
	emKOBJEVENTTYPE_DOODAD_BEGIN									= 0x00035000,
	emKOBJEVENTTYPE_DOODAD_ENTER_SCENE,
	emKOBJEVENTTYPE_DOODAD_LEAVE_SCENE,
	emKOBJEVENTTYPE_DOODAD_STATE_CHANGED,


	// ---------------------------------------------------------------------
	// Combat 事件
	emKOBJEVENTTYPE_COMBAT_BEGIN								= 0x00040000,
	emKOBJEVENTTYPE_COMBAT_SLIPCELL								= 0x00040001,			// 格子坐标变换，给UI用，获取要显示的格子列表
	emKOBJEVENTTYPE_COMBAT_CONFIRMCELL							= 0x00040002,			// 格子坐标确定，给UI用
	emKOBJEVENTTYPE_COMBAT_SLIPSEAT,													// 滑过初始站位
	emKOBJEVENTTYPE_COMBAT_CONFIRMSEAT,													// 选中初始站位
	emKOBJEVENTTYPE_COMBAT_SETSEAT,														// 开始选择初始站位
	emKOBJEVENTTYPE_COMBAT_ROUNDBEGIN,													// 回合开始	
	emKOBJEVENTTYPE_COMBAT_ROUNDEND,													// 回合结束
	emKOBJEVENTTYPE_COMBAT_SET_OP,														// 选择动作
	emKOBJEVENTTYPE_COMBAT_SET_OP_DONE,													// 选择动作结束
	emKOBJEVENTTYPE_COMBAT_PLAY_ACTION,													// 开始播放动作
	emKOBJEVENTTYPE_COMBAT_FINISH,														// 战斗结束
	emKOBJEVENTTYPE_COMBAT_ACCEPTEDSEAT,												// 服务端接受了站位信息
	emKOBJEVENTTYPE_COMBAT_EXEC_ACTION_DONE,											// 服务端完成了动作执行
	emKOBJEVENTTYPE_COMBAT_PLAY_ACTION_DONE,											// 播放动作结束，发给服务端
	emKOBJEVENTTYPE_COMBAT_START,														// 战斗开始
	emKOBJEVENTTYPE_COMBAT_CANCELSELCELL,												// 取消选择格子
	emKOBJEVENTTYPE_COMBAT_INIT,														// 战斗初始化，用于UI显示
	emKOBJEVENTTYPE_COMBAT_CHARACTER_EXIT,												// 某人退出了战斗
	emKOBJEVENTTYPE_COMBAT_OPENMOVING,													// 开场动画
	emKOBJEVENTTYPE_COMBAT_OPENMOVING_DONE,												// 开场动画结束
	emKOBJEVENTTYPE_COMBAT_SELECTACTION_DONE,											// 选择动作完成
	emKOBJEVENTTYPE_COMBAT_SYNC_OPDONE,													// 队友选择操作完成
	emKOBJEVENTTYPE_COMBAT_PLAY_STATE_DONE,												// 战场状态表现完成
	emKOBJEVENTTYPE_COMBAT_PREROUNDEND,                                                 // 回合快结束
	emKOBJEVENTTYPE_COMBAT_ACTIONS,                                                     // 选择的动作列表
	emKOBJEVENTTYPE_COMBAT_DAMAGESHOW,                                                  // 表现伤害显示
	emKOBJEVENTTYPE_COMBAT_LEAVE_BATTLE,                                                // 离开战场
	emKOBJEVENTTYPE_COMBAT_ONE_SET_OP_DONE,                                             // 某人选择动作结束
	emKOBJEVENTTYPE_COMBAT_BEGIN_ROUND_ACTION,                                          // 开始一个回合动作
	emKOBJEVENTTYPE_COMBAT_END_ROUND_ACTION,                                            // 结束一个回合动作
	emKOBJEVENTTYPE_COMBAT_CHARACTER_ATTRIBUTE_CHANGE,                                  // 战场中技能引起的生命值魔法变化事件
	// ---------------------------------------------------------------------
	// 魔法事件
	emKOBJEVENTTYPE_MAGIC_BEGIN									= 0x00050000,
	emKOBJEVENTTYPE_MAGIC_REVIVE,								// 复活
	emKOBJEVENTTYPE_MAGIC_SLEEP,								// 睡眠
	emKOBJEVENTTYPE_MAGIC_CHANGE_PHYSICS_ATTACK_POWER_BASE,		// 改变基础物理攻击力
	emKOBJEVENTTYPE_MAGIC_CHANGE_PHYSICS_ATTACK_POWER_PAC,		// 改变物理攻击力叠加百分比
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAGIC_ATTACK_POWER_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAGIC_ATTACK_POWER_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_PHYSICS_DEFENCE_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_PHYSICS_DEFENCE_PAC,					
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAGIC_DEFENCE_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAGIC_DEFENCE_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_HIT_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_HIT_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_DODGE_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_DODGE_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_CRITICAL_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_CRITICAL_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_DECRITICAL_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_DECRITICAL_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAXLIFE_BASE,
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAXLIFE_PAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_MAXMANA,
	emKOBJEVENTTYPE_MAGIC_CAUSE_DAMAGE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_HEAL,
	emKOBJEVENTTYPE_MAGIC_CAUSE_SHACKLE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_PETRIFY,
	emKOBJEVENTTYPE_MAGIC_CAUSE_DEATH,
	emKOBJEVENTTYPE_MAGIC_CAUSE_CONFUSION,
	emKOBJEVENTTYPE_MAGIC_CAUSE_REMOVEBUFFER,

	//add by wdb, 
	emKOBJEVENTTYPE_MAGIC_CAUSE_CAST_SKILL,
	emKOBJEVENTTYPE_MAGIC_CAUSE_IMMUNE_DEATH,
	emKOBJEVENTTYPE_MAGIC_CAUSE_SILENCE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_CHANGETARGETTOSELF,
	emKOBJEVENTTYPE_MAGIC_CAUSE_CHANGETARGET,
	emKOBJEVENTTYPE_MAGIC_CAUSE_DAMAGETRANSER,
	emKOBJEVENTTYPE_MAGIC_CHANGE_ACTIONLOCATION,
	emKOBJEVENTTYPE_MAGIC_CAUSE_TRANSFERDAMAGETOMANA,
	emKOBJEVENTTYPE_MAGIC_CAUSE_EXCHANGECURRENTLIFE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_TRANSFERDAMAGETOHEAL,
	emKOBJEVENTTYPE_MAGIC_CAUSE_TRANSFERHEALTODAMAGE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_TRANSFERLIFETOMANA,
	emKOBJEVENTTYPE_MAGIC_CHANGE_ACTIONSPEED,
	emKOBJEVENTTYPE_MAGIC_CAUSE_RATINGDAMAGE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_RATINGHEAL,	
	emKOBJEVENTTYPE_MAGIC_CHANGE_HEALEFFECTPAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_BEHEALEFFECTPAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_DAMAGEEFFECTPAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_BEDAMAGEEFFECTPAC,
	emKOBJEVENTTYPE_MAGIC_CAUSE_CHARM,
	emKOBJEVENTTYPE_MAGIC_CHANGE_DAMAGECLASSPAC,
	emKOBJEVENTTYPE_MAGIC_CHANGE_BEDAMAGECLASSPAC,	
	emKOBJEVENTTYPE_MAGIC_CAUSE_CURRENTLIFEADD,
	emKOBJEVENTTYPE_MAGIC_CAUSE_CURRENTLIFEPACADD,
	emKOBJEVENTTYPE_MAGIC_CAUSE_MANAADD,
	emKOBJEVENTTYPE_MAGIC_CAUSE_STATICINF,
	emKOBJEVENTTYPE_MAGIC_CHANGE_POTIONEFFECTPAC,
	// add by panhui begin
    emKOBJEVENTTYPE_MAGIC_CAUSE_REBOUNDWITHWHOLEDAMAGE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_REBOUNDWITHPARTDAMAGE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_IMMUNITY,
    emKOBJEVENTTYPE_MAGIC_CHANGE_BUFFER_EFFECTTIME,
	emKOBJEVENTTYPE_MAGIC_CHANGE_CRITMULTIPLEPAC,
    emKOBJEVENTTYPE_MAGIC_CAUSE_COUNTER,
    emKOBJEVENTTYPE_MAGIC_CAUSE_NODEATH,
	emKOBJEVENTTYPE_MAGIC_CHANGE_SKILLCOSTMPPAC,
	emKOBJEVENTTYPE_MAGIC_CAUSE_SKILLEXTRAEFFECT,
	emKOBJEVENTTYPE_MAGIC_CAUSE_STEALBUFFER,
	emKOBJEVENTTYPE_MAGIC_CAUSE_DIRECTDAMAGE,
	emKOBJEVENTTYPE_MAGIC_CAUSE_LIFESTEAL,
	emKOBJEVENTTYPE_MAGIC_CHANGE_BUFFERHIT,
	emKOBJEVENTTYPE_MAGIC_CHANGE_BUFFERBEHIT,
	emKOBJEVENTTYPE_MAGIC_CAUSE_PLAYSFX,
	emKOBJEVENTTYPE_MAGIC_CAUSE_NIRVANA,
	emKOBJEVENTTYPE_MAGIC_CAUSE_FIERCE,
	// end

	emKOBJEVENTTYPE_MAGIC_END,


	//装备道具事件
	emKOBJEVENTTYPE_ITEM_ADD									= 0x00060000,
	emKOBJEVENTTYPE_ITEM_REMOVE,
	emKOBJEVENTTYPE_RECIPE_ADD,
	emKOBJEVENTTYPE_RECIPE_REMOVE,
	emKOBJEVENTTYPE_RECIPE_SYNCLISTREADY,
	emKOBJEVENTTYPE_COMPOSE_RESULT,
	emKOBJEVENTTYPE_ITEM_PROP_MODIFY,
	emKOBJEVENTTYPE_ITEM_USE,
	emKOBJEVENTTYPE_ITEM_TRANSFORM,
	emKOBJEVENTTYPE_ITEM_TRANSFORMSELECT,
	emKOBJEVENTTYPE_ITEM_ADDSTAR,


	// 表现逻辑事件
	emKOBJEVENTTYPE_REPRESENT_BEGIN								= 0x00070000,
	emKOBJEVENTTYPE_REPRESENT_INITGAME,												// 初始化游戏场景
	emKOBJEVENTTYPE_REPRESENT_GOTO,													// 走到哪
	emKOBJEVENTTYPE_REPRESENT_SELECT_MODEL,										// 选中了一个模型
	emKOBJEVENTTYPE_REPRESENT_ENTER_MODEL,
	emKOBJEVENTTYPE_REPRESENT_LEAVE_MODEL,
	emKOBJEVENTTYPE_REPRESENT_NOTIFY_CANNTSEAT,										// 通知用于，不能站位
	emKOBJEVENTTYPE_REPRESENT_SKILLANI_FINISH,										// 技能动画播放结束
	emKOBJEVENTTYPE_REPRESENT_SKILLANI_READY,										// 技能动画准备完成
	emKOBJEVENTTYPE_REPRESENT_SET_CAMERATYPE,										// 设置摄像机类型（用于技能动画中的操作节点）
	emKOBJEVENTTYPE_REPRESENT_SET_POSTYPE,											// 设置位置类型（用于技能动画中的操作节点）
	emKOBJEVENTTYPE_REPRESENT_CAMERA_MOVE,											// 镜头拖动
	emKOBJEVENTTYPE_REPRESENT_LBUTTONDOWN,											// 场景里鼠标左键按下
	emKOBJEVENTTYPE_REPRESENT_ADDMODEL,												// 模型添加事件
	emKOBJEVENTTYPE_REPRESENT_DELMODEL,												// 模型删除事件
	emKOBJEVENTTYPE_REPRESENT_RBTN_SELECT_MODEL,									// 右键选中了一个模型

	emKOBJEVENTTYPE_REPRESENT_END,
	//聊天事件
	emKOBJEVENTTYPE_CHAT_CHANNEL								= 0x00080000,
	emKOBJEVENTTYPE_CHAT_PLAYER_INFO_ARRIVAL,

	//队伍事件
	emKOBJEVENTTYPE_TEAM										= 0x00090000,
	emKOBJEVENTTYPE_LOGIN_TEAM,
	emKOBJEVENTTYPE_LOGOUT_TEAM,
	emKOBJEVENTTYPE_CREATED_TEAM,		//自己创建队伍
	emKOBJEVENTTYPE_JOIN_TEAM,			//加入别人队伍
	emKOBJEVENTTYPE_LEAVE_TEAM,			//离开队伍
	emKOBJEVENTTYPE_DISBAND_TEAM,		//解散队伍(目前仅GS端有)
	emKOBJEVENTTYPE_CAPTAIN_CHANGE,		//队长移交
	emKOBJEVENTTYPE_TEAM_MEMBER_CHANGED,
	emKOBJEVENTTYPE_TEAM_SEARCH_INFO,
	emKOBJEVENTTYPE_SELF_SEARCH_INFO,
	emKOBJEVENTTYPE_TEAM_DISABLE_STATE,
	emKOBJEVENTTYPE_TEAM_GROUP_CHANGED,
	emKOBJEVENTTYPE_TEAM_NEAR_BY_TEAM_UPDATED,
	emKOBJEVENTTYPE_SUMMON_MEMBER,
	emKOBJEVENTTYPE_REPLY_SUMMON,
	emKOBJEVENTTYPE_TEAM_NAME_UPDATE,
	emKOBJEVENTTYPE_FOLLOW_STATE_CHG,	//跟随状态改变
	emKOBJEVENTTYPE_TEAM_STATE_CHG,	//队伍状态改变

	//任务事件
	emKOBJEVENTTYPE_TASK_BEGIN									= 0x000A0000,
	emKOBJEVENTTYPE_TASK_ACCEPT,		//接受任务（包括主动接受和被共享接受）
	emKOBJEVENTTYPE_TASK_SHARE,			//共享任务给别人(todo 暂未支持)
	emKOBJEVENTTYPE_TASK_GIVEUP,		//放弃任务
	emKOBJEVENTTYPE_TASK_FINISH,		//完成任务
	emKOBJEVENTTYPE_TASK_RECOMMEND_REFRESH,		//推荐任务刷新
	emKOBJEVENTTYPE_TASK_SYNCDATAFINISHED,			// 任务数据同步完毕
	emKOBJEVENTTYPE_TASK_COMPLETE,		//任务进度完成（未交）
	emKOBJEVENTTYPE_TASK_END,

	//商店事件
	emKOBJEVENTTYPE_SHOP_BEGIN									= 0x000B0000,
	emKOBJEVENTTYPE_SHOP_OPENSHOP,
	emKOBJEVENTTYPE_SHOP_CLOSESHOP,
	emKOBJEVENTTYPE_SHOP_SYNCSHOPDATAFINISH,
	
	emKOBJEVENTTYPE_IBSHOP_OPENWINDOW,
	emKOBJEVENTTYPE_IBSHOP_CLOSEWINDOW,

	//钱袋
	emKOBJEVENTTYPE_PURSE_BEGIN									= 0x000C0000,
	emKOBJEVENTTYPE_PURSE_CHANGECURRENCY,
	emKOBJEVENTTYPE_PURSE_CHANGECOIN,
	emKOBJEVENTTYPE_PURSE_CHANGEMONEY,
	// ---------------------------------------------------------------------

	//职业事件
	emKOBJEVENTTYPE_FACTION_BEGIN								= 0x000D0000,
	emKOBJEVENTTYPE_FACTION_BINDSKILL_CHANGED,		//服务器端发来绑定技能变化
	emKOBJEVENTTYPE_FACTION_EXP_CHANGED,			// 职业经验有改变
	emKOBJEVENTTYPE_FACTION_LEVEL_CHANGED,			// 职业等级有改变
	emKOBJEVENTTYPE_FACTION_SKILL_POWER_CHANGED,	// 职业秘笈点有改变

	// ---------------------------------------------------------------------
	// 聊天群
	emKOBJEVENTTYPE_GROUP_BEGIN									= 0x000E0000,
	emKOBJEVENTTYPE_GROUP_CREATE_GROUP,
	emKOBJEVENTTYPE_GROUP_DELETE_GROUP,
	emKOBJEVENTTYPE_GROUP_ADD_MEMBER,
	emKOBJEVENTTYPE_GROUP_REMOVE_MEMBER,
	emKOBJEVENTTYPE_GROUP_JOIN_REQUISITION,
	emKOBJEVENTTYPE_GROUP_ERROR_INFO,
	emKOBJEVENTTYPE_GROUP_GROUP_INFO,

	// 剧情事件   
	emKOBJEVENTTYPE_PLOT_PLAY_START                             = 0x000F0000,
	emKOBJEVENTTYPE_PLOT_PLAY_FINISH,

	// 全局变量
	emKOBJEVENTTYPE_GOLBALDATA_BEGIN							= 0x00100000,
	emKOBJEVENTTYPE_GLOBALDATA_INTVALUECHANGE					= 0x00100001,
	emKOBJEVENTTYPE_GLOBALDATA_BINVALUECHANGE					= 0x00100002,
	emKOBJEVENTTYPE_GLOBALDATA_DATA_SYNC_FINISH					= 0x00100003,

	// Story故事
	emKOBJEVENTTYPE_STORY_BEGIN									= 0x00110000,
	emKOBJEVENTTYPE_STORY_FINISH,
	emKOBJEVENTTYPE_STORY_PROGRESS_FINISH,

	// ExpScene副本/探索地图
	emKOBJEVENTTYPE_EXPSCENE_BEGIN								= 0x00120000,
	emKOBJEVENTTYPE_EXPSCENE_FINISH,
	emKOBJEVENTTYPE_EXPSCENE_CHANGE,
	emKOBJEVENTTYPE_EXPSCENE_UPDATE_STAR,

	//联赛事件
	emKOBJEVENTTYPE_LEAGUE_INFO_REACH							= 0x00130000,	//联赛信息到达客户端
	emKOBJEVENTTYPE_LEAGUE_PAGE_REACH,											//联赛排名数据到达客户端
	emKOBJEVENTTYPE_LEAGUE_QUEUE_FLAG_CHG,										//通知UI联赛报名标志改变

	//人际事件
	emKOBJEVENTTYPE_RELATION_LIST_REACH							= 0x00140000,	//人际关系列表到达客户端
	emKOBJEVENTTYPE_RELATION_INFO_REACH,										//人际关系玩家详细信息
	emKOBJEVENTTYPE_RELATION_SIGNATURE_CHG,										//自己签名已修改
	emKOBJEVENTTYPE_RELATION_MOOD_CHG,											//自己心情已修改
	emKOBJEVENTTYPE_RELATION_REMOVE,											//关系已解除
	emKOBJEVENTTYPE_RELATION_ADD,												//关系已建立
	emKOBJEVENTTYPE_RELATION_ONLINE_CHG,										//好友上下线

	// 宠物事件
	emKOBJEVENTTYPE_SUB_ADDSUB										= 0x00150000,
	emKOBJEVENTTYPE_SUB_DELSUB,
	emKOBJEVENTTYPE_SUB_RESPONSE_SUBDATA,
	emKOBJEVENTTYPE_SUB_STARTWORK,
	emKOBJEVENTTYPE_SUB_STOPWORK,
	emKOBJEVENTTYPE_SUB_AWARD_INFORM,
	emKOBJEVENTTYPE_SUB_POSSESS,
	emKOBJEVENTTYPE_SUB_UNPOSSESS,
	emKOBJEVENTTYPE_SUB_ACCEPT_AWARD_BYSUB,
	emKOBJEVENTTYPE_SUB_ACCEPT_AWARD,
	emKOBJEVENTTYPE_SUB_MUDS_ONESUB,
	emKOBJEVENTTYPE_SUB_MUDS_ALLSUB,
	emKOBJEVENTTYPE_SUB_PROLONGWORK,
	emKOBJEVENTTYPE_SUB_MAINSUB_CHANAGED,
	emKOBJEVENTTYPE_SUB_FOLLOWSUB_CHANGED,
	emKOBJEVENTTYPE_SUB_UPDATE_ADDPOINT,
	emKOBJEVENTTYPE_SUB_PROP_CHANGED,

	// 家族事件
	emKOBJEVENTTYPE_KIN_CREATE									= 0x00160000,	//创建家族
	emKOBJEVENTTYPE_KIN_DESTROY,
	emKOBJEVENTTYPE_KIN_DETECTDESTROY,
	emKOBJEVENTTYPE_KIN_INVITE,
	emKOBJEVENTTYPE_KIN_REFUSEINVITE,
	emKOBJEVENTTYPE_KIN_APPLYADDKIN,
	emKOBJEVENTTYPE_KIN_APPROVEADDKIN,											//批准加入家族
	emKOBJEVENTTYPE_KIN_KICKOUT,												//踢出家族
	emKOBJEVENTTYPE_KIN_QUIT,													//退出家族
	emKOBJEVENTTYPE_KIN_TRYCHANGEGROUP,											//人员调整尝试
	emKOBJEVENTTYPE_KIN_CHANGEGROUP,											//人员调整
	emKOBJEVENTTYPE_KIN_CHANGEFIGURE,											//职位调整
	emKOBJEVENTTYPE_KIN_APPLYKININFO,											//请求家族信息
	emKOBJEVENTTYPE_KIN_APPLYKININFOEX,											//请求家族信息
	emKOBJEVENTTYPE_KIN_APPLYKINMEMBERINFO,										//请求家族成员信息
	emKOBJEVENTTYPE_KIN_APPLYKINAPPLYLIST,										//请求申请加入家族列表
	emKOBJEVENTTYPE_KIN_CHANGEKININFO,											//修改家族信息
	emKOBJEVENTTYPE_KIN_GETKINID,												//获取家族Id
	emKOBJEVENTTYPE_KIN_LOGIN,													//成员登陆
	emKOBJEVENTTYPE_KIN_LOGOUT,													//成员登出
	emKOBJEVENTTYPE_KIN_KININFOCHANGE,											//家族信息发生变化
	emKOBJEVENTTYPE_KIN_TRIALRESULT,											//家族考验期结果通知
	emKOBJEVENTTYPE_KIN_GROUPRESULT,											//家族团队成长结果通知
	emKOBJEVENTTYPE_KIN_APPLYKINWORKLIST,								//申请家族事务列表
	emKOBJEVENTTYPE_KIN_APPLYKINWORKVOTEINFO,					//申请家族事务投票信息
	emKOBJEVENTTYPE_KIN_VOTE,															//投票
	emKOBJEVENTTYPE_KIN_ADDVOTEOPTION,									//增加投票选项
	emKOBJEVENTTYPE_KIN_DOWORK,													//开启事务
	emKOBJEVENTTYPE_KIN_DOWORKRESULT,									//事务执行结果
	emKOBJEVENTTYPE_KIN_ADDDEVOTE,											//增加贡献值
	emKOBJEVENTTYPE_KIN_APPLYDEVOTEINFO,								//申请贡献值信息
	emKOBJEVENTTYPE_KIN_FUNCCHANGE,											//家族功能开启关闭
	emKOBJEVENTTYPE_KIN_CANCELCAPTAINQUIT,							//取消团长退出
	emKOBJEVENTTYPE_KIN_CHANGERECRUIT,									//招募改变
	emKOBJEVENTTYPE_KIN_SEARCHRECRUIT,									//查询招募
	emKOBJEVENTTYPE_KIN_TRIALNOTIFYRESULT,								//考验期提示

	// 邮件事件
	emKOBJEVENTTYPE_MAIL_LOADOK									= 0x00170000,	//邮箱加载完成
	emKOBJEVENTTYPE_MAIL_SYNCLIST,												//同步邮件列表
	emKOBJEVENTTYPE_MAIL_NEW,													//有新邮件
	emKOBJEVENTTYPE_MAIL_SENDRESULT,											//邮件发送结果
	emKOBJEVENTTYPE_MAIL_SYNCCONTENT,											//同步邮件内容
	emKOBJEVENTTYPE_MAIL_NEWDELIVERY,											//有急件

	emKOBJEVENTTYPE_GATHER_BEGIN								= 0x00180000,
	emKOBJEVENTTYPE_GATHER_READY,
	emKOBJEVENTTYPE_GATHER_FINISH,

	emKOBJEVENTTYPE_BUFF_BUFF_IN                                = 0x00190000,		// 添加buff事件
	emKOBJEVENTTYPE_BUFF_BUFF_OUT,													// 删除buff事件
	emKOBJEVENTTYPE_BUFF_DMG_IN,
	emKOBJEVENTTYPE_BUFF_DMG_OUT,
	emKOBJEVENTTYPE_BUFF_DEATH,                     
	emKOBJEVENTTYPE_BUFF_KILL,
	emKOBJEVENTTYPE_BUFF_BUFF_PILE,                   // buff叠加层数改变
	emKOBJEVENTTYPE_BUFF_CRITICAL,
	emKOBJEVENTTYPE_BUFF_IS_BACK,
	emKOBJEVENTTYPE_BUFF_MISS,
};


// -------------------------------------------------------------------------

