
#pragma once

#include <map>
#include "Runtime/qstring.h"
#include "config/kcharacterdef.h"
#include "onlinegameworld/kctrlfactory.h"
#include "onlinegameworld/ksceneobject.h"
#include "onlinegameworld/kcontainer.h"
#include "onlinegameworld/kobjeventsetting.h"
#include "onlinegameworld/kcharacterctrlbase.h"
#include "onlinegameworld/kcharacterserver.h"
#include "onlinegameworld/kcharacterclient.h"

#include "onlinegamemodule/ai/Target.h"
#include "../onlinegamemodule/award/awarddef.h"

// --------------------------------------------------------------------------

class KCharacter;
class KTCharacterCtrlFactory : public KTCtrlFactory<KCharacter, KCharacterCtrlBase, emKCHARACTER_CTRL_MAX>
{
public:
	VOID CreateCtrls(KCharacter& rcContainer, DWORD dwTypeMask);
};

// -------------------------------------------------------------------------

class KLuaCharacter;
class KCharacter : public KSceneObject
{
	friend class KLuaCharacter;
#define KD_CHARACTER_TASKFUN(_Name, _GroupId, _TaskId) \
	INT Get##_Name() const { return GetVar(_GroupId, _TaskId); } \
	BOOL Set##_Name(INT n##_Name) { return SetVar(_GroupId, _TaskId, n##_Name); }	\
	BOOL RawSet##_Name(INT n##_Name) { return SetVar(_GroupId, _TaskId, n##_Name, FALSE); }	\
	BOOL Add##_Name(INT n##_Name) { return AddVar(_GroupId, _TaskId, n##_Name); } \
	BOOL RawAdd##_Name(INT n##_Name) { return AddVar(_GroupId, _TaskId, n##_Name, FALSE); }
	// 带U的变量在Add时会检查是否溢出，若会溢出默认不处理并返回FALSE
#define KD_CHARACTER_TASKFUN_U(_Name, _GroupId, _TaskId) \
	INT Get##_Name() const { return GetVar(_GroupId, _TaskId); } \
	BOOL Set##_Name(INT n##_Name) { return SetVar(_GroupId, _TaskId, n##_Name); }	\
	BOOL RawSet##_Name(INT n##_Name) { return SetVar(_GroupId, _TaskId, n##_Name, FALSE); }	\
	BOOL Add##_Name(INT n##_Name) { return AddVarU(_GroupId, _TaskId, n##_Name); } \
	BOOL RawAdd##_Name(INT n##_Name) { return AddVarU(_GroupId, _TaskId, n##_Name, FALSE); } \
	// 标志位映射，标志位变量只能用DWORD型变量
#define KD_CHARACTER_TASKFUN_FLAG(_Name, _TaskId, _Flag) \
	BOOL Get##_Name() const { return  m_cContainer.m_cDwArrayValue.GetFlag(_TaskId, _Flag); } \
	VOID Set##_Name(BOOL bSet) { m_cContainer.m_cDwArrayValue.SetFlag(_TaskId, _Flag, bSet); }
public:
	// TODO:This is Dirty
	KD_CHARACTER_TASKFUN(Sex,						emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_SEX)

	KD_CHARACTER_TASKFUN(CurrentRoute,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_CURRENT_ROUTE)
	KD_CHARACTER_TASKFUN(CurrentCamp,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_CURRENT_CAMP)
	KD_CHARACTER_TASKFUN(KinCamp,				    emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_KIN_CAMP)

	KD_CHARACTER_TASKFUN(OccupationCoefficient,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_OCCUPATION_COEFFICIENT		)
	KD_CHARACTER_TASKFUN(IsStun,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_STUN							)
	KD_CHARACTER_TASKFUN(IsFix,						emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_FIX							)
	KD_CHARACTER_TASKFUN(IsFear,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_FEAR							)
	KD_CHARACTER_TASKFUN(IsSilence,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_SILENCE						)
	KD_CHARACTER_TASKFUN(IsCrazy,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_CRAZY							)
	KD_CHARACTER_TASKFUN(IsHidetoNPC,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_HIDE_TO_NPC					)
	KD_CHARACTER_TASKFUN(IsHidetoPlayer,			emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_HIDE_TO_PLAYER				)
	KD_CHARACTER_TASKFUN(IsVisiontoNPC,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_VISION_TO_NPC					)
	KD_CHARACTER_TASKFUN(IsVisiontoPlayer,			emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_VISION_TO_PLAYER				)
	KD_CHARACTER_TASKFUN(IgnorDmg,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_IGNOR_DMG						)
	KD_CHARACTER_TASKFUN(IgnorCristal,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_IGNOR_CRISTAL					)
	KD_CHARACTER_TASKFUN(IgnorDebuff,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_IGNOR_DEBUFF					)
	KD_CHARACTER_TASKFUN(IsRide,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_RIDE							)
	KD_CHARACTER_TASKFUN(IsFightMap,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_IS_FIGHT_MAP					)
	KD_CHARACTER_TASKFUN(PetCapacity,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_PET_CAPACITY					)
	KD_CHARACTER_TASKFUN(VipLevel,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_VIP_LEVEL						)
	KD_CHARACTER_TASKFUN(MissionState,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_MISSION_STATE					)
	KD_CHARACTER_TASKFUN(EightTrigramLevel1,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_1			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel2,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_2			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel3,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_3			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel4,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_4			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel5,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_5			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel6,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_6			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel7,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_7			)
	KD_CHARACTER_TASKFUN(EightTrigramLevel8,		emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_8			)
	KD_CHARACTER_TASKFUN(EightTrigramLevelTaiChi,	emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_TAICHI	)
	KD_CHARACTER_TASKFUN(MeditationState,			emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_MEDITATION_STATE				)
	KD_CHARACTER_TASKFUN(IsSetFightMode,			emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_IS_SET_FIGHT_MODE				)
	KD_CHARACTER_TASKFUN(MopState,					emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_MOP_STATE						)
	KD_CHARACTER_TASKFUN(Anger,						emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_ANGER							)
	KD_CHARACTER_TASKFUN(EscortType,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_ESCORT_TYPE					)
	KD_CHARACTER_TASKFUN(EscortState,				emKVARGROUP_CHARACTER_BYTE,		emKCHARACTER_TASK_ESCORT_STATE					)

	KD_CHARACTER_TASKFUN(PrimaryFaction,			emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_PRIMARY_FACTION)
	KD_CHARACTER_TASKFUN_U(Level,					emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_LEVEL)
	KD_CHARACTER_TASKFUN_U(HatRepresentId,			emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_HAT_REPRESENTID)	
	KD_CHARACTER_TASKFUN_U(BodyRepresentId,			emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_BODY_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(LeftWeaponRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_LEFTWEAPON_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(RightWeaponRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_RIGHTWEAPON_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(BackPendantRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_BACKPENDANT_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(HeadPendantRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_HEADPENDANT_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(BottomPendantRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_BOTTOMPENDANT_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(LeftShoulderRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_LEFT_SHOULDER_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(RightShoulerRepresentId,	emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_RIGHT_SHOULDER_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(RideRepresentId,			emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_RIDE_REPRESENTID)
	KD_CHARACTER_TASKFUN_U(PetRepresentId,			emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_PET_REPRESENTID)
	KD_CHARACTER_TASKFUN(ArenaRank,					emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_ARENA_RANK_NUM)
	KD_CHARACTER_TASKFUN(TowerLayer,				emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_CONQUER_TOWER_LAYER)
	KD_CHARACTER_TASKFUN(TitleCarry1,				emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_TITLE_CARRY_1)
	KD_CHARACTER_TASKFUN(TitleCarry2,				emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_TITLE_CARRY_2)
	KD_CHARACTER_TASKFUN(TitleCarry3,				emKVARGROUP_CHARACTER_WORD,		emKCHARACTER_TASK_TITLE_CARRY_3)

	KD_CHARACTER_TASKFUN(Exp,						emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_EXP)
	KD_CHARACTER_TASKFUN(CurrentLife,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURRENT_LIFE)
	KD_CHARACTER_TASKFUN(CurrentMana,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURRENT_MANA)
	KD_CHARACTER_TASKFUN(CurrentPower,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURRENT_POWER)
	KD_CHARACTER_TASKFUN(ExtBag,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_EXT_BAG)
	KD_CHARACTER_TASKFUN(LastUpdateEscortTime,		emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_LAST_UPDATE_ESCORT_TIME)
	KD_CHARACTER_TASKFUN(CurEscortTaskId,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CUR_ESCORT_TASK_ID)
	KD_CHARACTER_TASKFUN(ReceivedEscortTaskId,		emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_RECEIVED_ESCORT_TASK_ID)
	KD_CHARACTER_TASKFUN(EscortAwardTotalExp,		emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_ESCORT_AWARD_TOTAL_EXP)
	KD_CHARACTER_TASKFUN(EscortAwardTotalEnergy,	emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_ESCORT_AWARD_TOTAL_ENERGY)
	KD_CHARACTER_TASKFUN(LastUpdateBowlFreeTime,	emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_LAST_UPDATE_BOWL_FREE_TIME)
	KD_CHARACTER_TASKFUN(BowlFreeCumulativeTime,	emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_BOWL_FREE_CUMULATIVE_TIME)

	KD_CHARACTER_TASKFUN(LastLogoutTime,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_LAST_LOGOUT_TIME)
	KD_CHARACTER_TASKFUN(LastLoginTime,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_LAST_LOGIN_TIME)
	KD_CHARACTER_TASKFUN(BanChatEndTime,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_BAN_CHAT_END_TIME)

	KD_CHARACTER_TASKFUN_U(MaxLife,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_MAX_LIFE)
	KD_CHARACTER_TASKFUN_U(MaxMana,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_MAX_MANA)
	KD_CHARACTER_TASKFUN_U(MaxPower,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_MAX_POWER)
	
	KD_CHARACTER_TASKFUN(Attack,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_ATTACK_ABILITY				)
	KD_CHARACTER_TASKFUN(HitCoefficient,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_HITCOEFFICIENT				)
	KD_CHARACTER_TASKFUN(Dodge,						emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_DODGE_ABILITY					)
	KD_CHARACTER_TASKFUN(Def,						emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_DEF_ABILITY					)
	KD_CHARACTER_TASKFUN(Speed,						emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_SPEED_ABILITY					)
	KD_CHARACTER_TASKFUN(SpeedDelaySet,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_SPEEDDELAYSET			    )
	
	KD_CHARACTER_TASKFUN(CriticalValue,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CRITICAL_VALUE				)
	KD_CHARACTER_TASKFUN(CriticalAttack,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CRITICAL_ABILITY				)
	KD_CHARACTER_TASKFUN(Resist,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_RESIST						)
	KD_CHARACTER_TASKFUN(CriticalDeAttack,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CRITICAL_DEABILITY			)
	KD_CHARACTER_TASKFUN(IgnoreDef,				    emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_IGNORE_DEF					)
																															
	KD_CHARACTER_TASKFUN(CuringLifeBase,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURING_LIFE_BASE				)
	KD_CHARACTER_TASKFUN(CuringLife,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURING_LIFE					)
	KD_CHARACTER_TASKFUN(CuringManaBase,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURING_MANA_BASE				)
	KD_CHARACTER_TASKFUN(CuringMana,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_CURING_MANA					)

	KD_CHARACTER_TASKFUN(WithstandNormalP,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_WITHSTAND_NORMAL_P			)
	KD_CHARACTER_TASKFUN(WithstandNormalV,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_WITHSTAND_NORMAL_V			)
	KD_CHARACTER_TASKFUN(ReboundP,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_REBOUND_P						)
	KD_CHARACTER_TASKFUN(ReboundV,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_REBOUND_V						)
	KD_CHARACTER_TASKFUN(TransToLifeP,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_TRANSTOLIFE_P					)
	KD_CHARACTER_TASKFUN(TransToManaP,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_TRANSTOMANA_P					)
	KD_CHARACTER_TASKFUN(EnlargeAttackP,			emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_ENLARGE_ATTACK_P				)
	KD_CHARACTER_TASKFUN(ReduceAttackP,				emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_REDUCE_ATTACK_P				)

	KD_CHARACTER_TASKFUN(TeamId,					emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_TEAM_ID)

	KD_CHARACTER_TASKFUN(ChangeNameColor,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_CHANGE_NAME_COLOR)

 	KD_CHARACTER_TASKFUN(AIType,					emKVARGROUP_CHARACTER_DWORD,	emKCHARACTER_TASK_AI_TYPE)
 	KD_CHARACTER_TASKFUN(Relation,                  emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_RELATION)
	KD_CHARACTER_TASKFUN(CurrentDamage,             emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_CURRENT_DAMAGE)
	KD_CHARACTER_TASKFUN(ModifyDmgP,				emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_MODIFYDMG_P)
	KD_CHARACTER_TASKFUN(MedicineEffect,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_MEDICINE_EFFECT)
	

	// Add By ZZ
	KD_CHARACTER_TASKFUN(WorldSpeakerCount,			emKVARGROUP_CHARACTER_MAP,      emKCHARACTER_CHAT_WORLD_SPEAKER)
	KD_CHARACTER_TASKFUN(WorldFreeSpeakerCount,		emKVARGROUP_CHARACTER_MAP,      emKCHARACTER_CHAT_WORLD_FREESPEAKER)
	KD_CHARACTER_TASKFUN(WorldFreeSpeakerResetTime,	emKVARGROUP_CHARACTER_MAP,      emKCHARACTER_CHAT_WORLD_FREESPEAKER_RESETTIME)
	KD_CHARACTER_TASKFUN(GlobalSpeakerCount,		emKVARGROUP_CHARACTER_MAP,      emKCHARACTER_CHAT_GLOBAL_SPEAKER)
	KD_CHARACTER_TASKFUN(LevelDifficuty,		    emKVARGROUP_CHARACTER_MAP,      emCHARACTER_LEVEL_DIFFICUTY)

	KD_CHARACTER_TASKFUN(FactionBattleRank,		    emKVARGROUP_CHARACTER_MAP,      emCHARACTER_FACTION_BATTLE_RANK)
	KD_CHARACTER_TASKFUN(GlobalBattleScore,		    emKVARGROUP_CHARACTER_MAP,      emCHARACTER_GLOBAL_BATTLE_SCORE)
	KD_CHARACTER_TASKFUN(LastQuitTongTime,		    emKVARGROUP_CHARACTER_DWORD,    emCHARACTER_LAST_QUIT_TONG_TIME)

	KD_CHARACTER_TASKFUN(EnableEnemyCondition,		emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ENABLE_ENYMY_CONDITION)
	KD_CHARACTER_TASKFUN(EnemyCondition1,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ENYMY_CONDITION1)
	KD_CHARACTER_TASKFUN(EnemyCondition2,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ENYMY_CONDITION2)
	KD_CHARACTER_TASKFUN(EnemyCondition3,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ENYMY_CONDITION3)
	KD_CHARACTER_TASKFUN(EnemyCondition4,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ENYMY_CONDITION4)
	KD_CHARACTER_TASKFUN(EnemyCondition5,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ENYMY_CONDITION5)

	KD_CHARACTER_TASKFUN(FightScore,				emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_FIGHT_SCORE)

	KD_CHARACTER_TASKFUN(LastTeamMsgTime,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_LAST_TEAM_MSG_TIME)
	KD_CHARACTER_TASKFUN(OverallTeamIdx,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_OVERALL_TEAM_IDX)
	KD_CHARACTER_TASKFUN(AngerLeftTime,				emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_ANGER_LEFT_TIME)
	KD_CHARACTER_TASKFUN(MultiMapId,				emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_MULTI_MAP_ID)
	KD_CHARACTER_TASKFUN(LastTakeMakeupTime,		emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_LAST_TAKE_MAKEUP_TIME)


	//日常任务
	KD_CHARACTER_TASKFUN(Dtask1,			       	emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK1)
	KD_CHARACTER_TASKFUN(Dtask2,					emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK2)
	KD_CHARACTER_TASKFUN(Dtask3,					emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK3)
	KD_CHARACTER_TASKFUN(Dtask4,					emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK4)
	KD_CHARACTER_TASKFUN(DtaskRefreshTime,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK_REFRESH_TIME)
	KD_CHARACTER_TASKFUN(DtaskTimesRefreshTime,		emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK_TIMES_REFRESH_TIME)
	KD_CHARACTER_TASKFUN(DtaskUsedTimes,			emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_DTASK_USED_TIMES)


	//微端登录
	KD_CHARACTER_TASKFUN(TinyTerminal,			    emKVARGROUP_CHARACTER_DWORD,    emKCHARACTER_TASK_TINY_TERMINAL)
	
	// End

	// 根据Group和Id获取、设置变量
	// 下面三个函数可设置程序内置变量及（脚本）扩展变量，程序内置Group见KE_BASE_VAR_GROUP定义
	// 若需无符号值，需对返回值作UINT转换
	// 这里Group和Id定义暂时用WORD，事实上现取值范围均为BYTE
	INT GetVar(WORD wVarGroup, WORD wVarId) const;
	BOOL SetVar(WORD wVarGroup, WORD wVarId, INT nValue, BOOL bSync = TRUE);
	// 增加\减少某个变量值，返回结果值
	BOOL AddVar(WORD wVarGroup, WORD wVarId, INT nAdd, BOOL bSync = TRUE);
	// 增加\减少某个变量值（用于无符号型），并检查溢出，或溢出则设置失败返回FALSE
	BOOL AddVarU(WORD wVarGroup, WORD wVarId, INT nAdd, BOOL bSync = TRUE);
	// 直接设置变量值，不判断自动同步，重载回调等
	BOOL RawSetVar(WORD wVarGroup, WORD wVarId, INT nValue);
public:	
#ifdef GAME_SERVER
	KCharacter(KCharacterServer& rCtrl, DWORD dwTypeMask, INT nRoleVarMax);
	KCharacterServer& m_cCharacterServer;
#else
	KCharacter(KCharacterClient& rCtrl, DWORD dwTypeMask, INT nRoleVarMax);
	KCharacterClient& m_cCharacterClient;
#endif

	virtual ~KCharacter();

	virtual	BOOL	Init();
	virtual	BOOL	Uninit();
	virtual	BOOL	Activate();

	virtual	BOOL	GoTo(INT nX, INT nY, INT nZ, BOOL bSyncSelf = FALSE)	PURE;
	virtual	BOOL	StopMove(BOOL bSyncSelf = FALSE) PURE;
	virtual	BOOL	Jump(BOOL bSyncSelf = FALSE)	PURE;
	virtual	BOOL	KnockTo(INT nX, INT nY, INT nZ, INT nDirection)	PURE;
	virtual BOOL	Pull(INT nX, INT nY, INT nZ, INT nDirection) PURE;
	virtual	BOOL	ChangeFaceDirection(INT nFaceDirection, BOOL bSync = TRUE);
	virtual	BOOL	OnReachTarget();

	virtual	BOOL	OnMoveStateChanged(KE_MOVE_STATE eMoveState);
	virtual	BOOL	LogicGoTo(INT nX, INT nY, INT nZ) { return GoTo(nX, nY, nZ); } // TODO
	virtual	INT		GetMoveSpeed() const;
	virtual	BOOL	SetMoveSpeed(INT nMoveSpeed, BOOL bSyncToClient = TRUE);
	BOOL	SetRideState(BYTE bRide);
	BOOL	GetRideState();
	virtual KLuaCharacter* GetScriptInterface() {return m_pLuna;}

	//typedef KTCtrlFactory<KCharacter, KCharacterCtrlBase, emKCHARACTER_CTRL_MAX> TCTRL_FACTORY;
	//typedef KTCharacterCtrlFactory TCTRL_FACTORY;
	template<class KTCTRL>
	KTCTRL* GetCtrl() { return m_cCtrlSet.GetCtrl<KTCTRL>(); }
	KCharacterCtrlBase* GetCtrl(INT nCtrlId) { return m_cCtrlSet.GetCtrl(nCtrlId); }
	KCharacterCtrlBase* TraverseNextCtrl(INT& rnCtrlId) { return m_cCtrlSet.TraverseNextCtrl(rnCtrlId); }

	VOID SetFirstTimeLogin(BOOL bFirstTimeLogin){ m_bFistTimeLogin = bFirstTimeLogin; }
	BOOL IsFirstTimeLogin() CONST { return m_bFistTimeLogin; }
	VOID SetSkillHidden(BOOL bHidden) { m_bSkillHidden = bHidden; }

	BOOL IsIgnoreDebuff(INT nBuffType);

	template<class KTCTRL>
	KTCTRL& GetCtrlRef()
	{
		KTCTRL* pCtrl = m_cCtrlSet.GetCtrl<KTCTRL>();
		assert(pCtrl);
		return *pCtrl;
	}
public:
	BOOL						m_bSystemShield;
	int                         m_nSelfAlarmRangeRevise;            // 对自身警戒范围的修正; 一般用于NPC
	int                         m_nOtherAlarmRangeRevise;           // 对他人警戒范围的修正 
	int                         m_nIgnoreOtherAlarmRange;           // 忽视他人(NPC)警戒范围
	int							m_nThreatTime;				        // 仇恨消退间隔

	KTarget                     m_SelectTarget;
	KTarget                     m_SkillTarget;
	int							m_nOverThreatPercent;
	std::vector<INT>            m_SpeedCheckArr;

	BOOL		m_bSkillHidden;	// 是否处于技能隐身状态（隐身技能，对友方可见）
protected:
	KTCharacterCtrlFactory m_cCtrlSet;
	KContainer m_cContainer;
	KTArrayValue<DWORD> m_cRoleValue;	// 实体对象（Player、Npc）的专有变量

	friend class KCharacterServer;
	friend class KCharacterClient;
#ifdef GAME_SERVER
//////////////////////////////////////////////////////////////////////////
// 场景技能所需接口
public:
	INT GetNearByNpcInSector(INT nRange, INT nAngle, INT nCount, DWORD* pNpcList);
	INT GetNearByPlayerInSector(INT nRange, INT nAngle, INT nCount, DWORD* pPlayerList);
	INT GetFrontPosition(INT nDistance, INT nDirection, INT &nX, INT &nY, INT &nZ);

	BOOL ModifyThreat(THREAT_TYPE eType, int nThreatValue);       // 用于技能直接修改对方仇恨值

	int  AdjustThreat(THREAT_TYPE eTheatType, int nThreatValue);  

	BOOL SelectTarget(TARGET_TYPE eTargetType, DWORD dwTargetID);

	BOOL Stand(BOOL bSyncSelf);

	BOOL IsSkillHidden(KCharacter *pCharacter);

#endif
	//是否可以移动
	virtual BOOL	CanMove();

private:
	KLuaCharacter* m_pLuna; // 脚本指针
	BOOL m_bFistTimeLogin; // 是否第一次登录

private:
	std::map<INT, FLOAT> m_mapFactionAttrValue;

public:
	FLOAT GetFactionAttrValue(INT nAttr);
	BOOL SetFactionAttrValue(INT nAttr, FLOAT fValue);

	BOOL ApplyNumericalAward(CONST QNumericalAward* pAward);
	BOOL RemoveNumericalAward(CONST QNumericalAward* pAward, BOOL bRawSet = FALSE);
};

// 变量变更事件指定重载函数定义（Map类型不支持指定重载函数）
typedef BOOL (*KT_CHARACTER_SET_FUN_DW)(KCharacter& rcCharacter, DWORD&, DWORD);
typedef BOOL (*KT_CHARACTER_SET_FUN_W)(KCharacter& rcCharacter, WORD&, WORD);
typedef BOOL (*KT_CHARACTER_SET_FUN_BY)(KCharacter& rcCharacter, BYTE&, BYTE);
// 现只有DW类型才能指定溢出重载函数
typedef BOOL (*KT_CHARACTER_ADD_OVERFLOW_FUN_DW)(KCharacter& rcCharacter, DWORD&, INT);

extern KT_CHARACTER_SET_FUN_DW g_aCharacterSetFunDw[256];
extern KT_CHARACTER_SET_FUN_W g_aCharacterSetFunW[256];
extern KT_CHARACTER_SET_FUN_BY g_aCharacterSetFunBy[256];
// -------------------------------------------------------------------------

//#pragma pack(push, 1)
//日常任务
//struct DTASK_DETAIL
//{
//	BYTE byTaskLevel;//任务等级
//	BYTE byTaskStatus;//任务状态 0.待接受  1.已接受  2. 已完成可领取奖励
//	BYTE byTaskTimes;//任务完成次数
//	BYTE byTaskId;//任务对应的基础任务编号
//};
//#pragma pack(pop)

int g_GetRelation(KCharacter* pSrcCharacter, KCharacter* pDstCharacter);
