
#pragma once

// -------------------------------------------------------------------------

enum KE_PURSE_S2C_PROTOCOL
{
	emPURSE_PTC_S2C_SYNC_CURRENCY,
	emPURSE_PTC_S2C_SYNC_REGIST_CURRENCYTYPE,	
	emPURSE_PTC_S2C_SYNC_MONEY,
	emPURSE_PTC_S2C_SYNC_REGIST_MONEYTYPE,
	emPURSE_PTC_S2C_SYNC_COIN,
	emPURSE_PTC_S2C_SYNC_AL_CHEMY,
	emPURSE_PTC_S2C_COUNT,
};


enum KE_PURSE_C2S_PROTOCOL
{
	emPURSE_PTC_C2S_SYNC_AL_CHEMY,
	emPURSE_PTC_C2S_COUNT,
};
