
#pragma once

// 阵营
enum KE_CAMP_TYPE
{
	emKCHARACTER_CAMP_NEUTRAL,		// 中立阵营
	emKCHARACTER_CAMP_PLAYER		= 1,		// 玩家阵营
	emKCHARACTER_CAMP_BATTLECAMP1	= 2,		// 战场阵营
	emKCHARACTER_CAMP_FIELD			= 3,		// 野外阵营
	emKCHARACTER_CAMP_ACTIVITY1		= 4,		// 活动1阵营
	emKCHARACTER_CAMP_ACTIVITY2	    = 5,		// 活动2阵营
	emKCHARACTER_CAMP_ACTIVITY3		= 6,		// 活动3阵营
	emKCHARACTER_CAMP_ACTIVITY4		= 7,		// 活动4阵营
	emKCHARACTER_CAMP_SLAUGHTER		= 8,		// 屠杀阵营
	emKCHARACTER_CAMP_PK			= 9,		// pk阵营
};

static const size_t RELATION_NUM = 4;	// 人物关系数量([1]自己、[2]队友、[3]敌人、[4]友方)

enum KE_SKILL_RELATION_DEF
{
	emRELATION_SELF = 1,
	emRELATION_TEAMMATE=2,
	emRELATION_ENEMY=3,
	emRELATION_FRIEND=4,
};

// --------------------------默认全部存盘，枚举不可变更，最大值255-------------------------------------
enum KE_CHARACTER_TASK_DEF_BYTE // 单字节类型 emKVARGROUP_CHARACTER_BYTE
{
	emKCHARACTER_TASK_SEX,								// 性别

	emKCHARACTER_TASK_CURRENT_ROUTE,					// 当前天赋路线
	emKCHARACTER_TASK_CURRENT_CAMP,						// 当前阵营
	emKCHARACTER_TASK_KIN_CAMP,                         // 家族阵营(仙、佛)

	emKCHARACTER_TASK_OCCUPATION_COEFFICIENT,			// 职业系数(仇恨用)
	emKCHARACTER_TASK_STUN,								// 眩晕
	emKCHARACTER_TASK_FIX,								// 定身
	emKCHARACTER_TASK_FEAR,								// 恐惧
	emKCHARACTER_TASK_SILENCE,							// 沉默
	emKCHARACTER_TASK_CRAZY,							// 疯狂
	emKCHARACTER_TASK_HIDE_TO_NPC,						// 对NPC隐藏
	emKCHARACTER_TASK_HIDE_TO_PLAYER,					// 对PLAYER隐藏
	emKCHARACTER_TASK_VISION_TO_NPC,					// 对NPC可见
	emKCHARACTER_TASK_VISION_TO_PLAYER,					// 对PLAYER可见
	emKCHARACTER_TASK_IGNOR_DMG,						// 免疫伤害
	emKCHARACTER_TASK_IGNOR_CRISTAL,					// 免疫会心一击
	emKCHARACTER_TASK_IGNOR_DEBUFF,						// 免疫所有debuff
	emKCHARACTER_TASK_RIDE,								// 骑马状态 add by NN
	emKCHARACTER_TASK_IS_FIGHT_MAP,						// 是否是战斗地图
	emKCHARACTER_TASK_PET_CAPACITY,						// 宠物栏数量
	emKCHARACTER_TASK_VIP_LEVEL,						// VIP等级
	emKCHARACTER_TASK_MISSION_STATE,					// 关卡和副本状态

	// 炼卦相关
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_1,				// 乾卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_2,				// 兑卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_3,				// 离卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_4,				// 震卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_5,				// 坤卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_6,				// 艮卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_7,				// 坎卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_8,				// 巽卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_TAICHI,			// 天地二仪
	
	emKCHARACTER_TASK_MEDITATION_STATE,						//打坐状态
	
	emKCHARACTER_TASK_IS_SET_FIGHT_MODE,					//是否可设置战斗模式: 和平、家族、pk模式
	emKCHARACTER_TASK_MOP_STATE,							// 扫荡状态

	emKCHARACTER_TASK_ANGER,								// 怒气值，最大100
	emKCHARACTER_TASK_ESCORT_TYPE,							// 修仙坐骑类型
	emKCHARACTER_TASK_ESCORT_STATE,							// 修仙状态

	emKCHARACTER_TASK_BYTE_MAX // 枚举数
};
// 配置需要同步给自己的变量，若修改需修改协议版本
const static WORD csByteVarSyncSelf[] =
{
	emKCHARACTER_TASK_SEX,								// 性别

	emKCHARACTER_TASK_CURRENT_ROUTE,					// 当前天赋路线
	emKCHARACTER_TASK_CURRENT_CAMP,						// 当前阵营
	emKCHARACTER_TASK_KIN_CAMP,
	emKCHARACTER_TASK_FIX,								// 定身
	emKCHARACTER_TASK_STUN,								// 眩晕
	emKCHARACTER_TASK_RIDE,								//  骑马状态
	emKCHARACTER_TASK_IS_FIGHT_MAP,						// 是否是战斗地图
	emKCHARACTER_TASK_PET_CAPACITY,						// 宠物栏数量
	emKCHARACTER_TASK_VIP_LEVEL,						// VIP等级
	emKCHARACTER_TASK_MISSION_STATE,

	// 炼卦相关
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_1,			// 乾卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_2,			// 兑卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_3,			// 离卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_4,			// 震卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_5,			// 坤卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_6,			// 艮卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_7,			// 坎卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_8,			// 巽卦
	emKCHARACTER_TASK_EIGHT_TRIGRAM_LEVEL_TAICHI,			// 天地二仪

	emKCHARACTER_TASK_MEDITATION_STATE,					//打坐
	emKCHARACTER_TASK_IS_SET_FIGHT_MODE,				//是否能设置战斗模式:家族、和平、pk
	emKCHARACTER_TASK_MOP_STATE,

	emKCHARACTER_TASK_ANGER,
	emKCHARACTER_TASK_ESCORT_TYPE,
	emKCHARACTER_TASK_ESCORT_STATE,

};
// 配置需要同步给他人（周围玩家）的变量，若修改需修改协议版本
const static WORD csByteVarSyncOther[] =
{
	emKCHARACTER_TASK_SEX,								// 性别

	emKCHARACTER_TASK_CURRENT_ROUTE,					// 当前天赋路线
	emKCHARACTER_TASK_CURRENT_CAMP,						// 当前阵营
	emKCHARACTER_TASK_KIN_CAMP,
	emKCHARACTER_TASK_FIX,								// 定身
	emKCHARACTER_TASK_STUN,								// 眩晕
	emKCHARACTER_TASK_RIDE,								//  骑马状态
	emKCHARACTER_TASK_IS_FIGHT_MAP,						// 是否是战斗地图
	emKCHARACTER_TASK_VIP_LEVEL,						// VIP等级
	emKCHARACTER_TASK_MEDITATION_STATE,					// 打坐
	emKCHARACTER_TASK_ANGER,
};

//---------------------------默认全部存盘，枚举不可变更，最大值255---------------------------------------
enum KE_CHARACTER_TASK_DEF_WORD // 双字节类型 emKVARGROUP_CHARACTER_WORD
{
	emKCHARACTER_TASK_LEVEL,
	emKCHARACTER_TASK_PRIMARY_FACTION,			// 主职业
	emKCHARACTER_TASK_HAT_REPRESENTID,			// 头部资源id
	emKCHARACTER_TASK_BODY_REPRESENTID,			// 身体资源id
	emKCHARACTER_TASK_LEFTWEAPON_REPRESENTID,	// 左手武器资源id
	emKCHARACTER_TASK_RIGHTWEAPON_REPRESENTID,	// 右手武器资源id
	emKCHARACTER_TASK_BACKPENDANT_REPRESENTID,	// 背部挂件id
	emKCHARACTER_TASK_HEADPENDANT_REPRESENTID,	// 头顶挂件id
	emKCHARACTER_TASK_BOTTOMPENDANT_REPRESENTID,	// 脚底挂件id
	emKCHARACTER_TASK_LEFT_SHOULDER_REPRESENTID, // 左肩
	emKCHARACTER_TASK_RIGHT_SHOULDER_REPRESENTID,// 右肩
	emKCHARACTER_TASK_RIDE_REPRESENTID,			// 坐骑id
	emKCHARACTER_TASK_PET_REPRESENTID,			// 宠物id
	emKCHARACTER_TASK_ARENA_RANK_NUM,			//竞技场排名
	emKCHARACTER_TASK_CONQUER_TOWER_LAYER,		// 伐魔塔层数
	emKCHARACTER_TASK_TITLE_CARRY_1,			//正在使用的称号1
	emKCHARACTER_TASK_TITLE_CARRY_2,			//正在使用的称号2
	emKCHARACTER_TASK_TITLE_CARRY_3,			//正在使用的称号3
	emKCHARACTER_TASK_WORD_MAX // 枚举数
};
// 配置需要同步给自己的变量，若修改需修改协议版本, 见kprotocol.h KD_PROTOCOL_VERSION和KD_PROTOCOL_VERSION_LOWER_LIMIT
const static WORD csWordVarSyncSelf[] =
{
	emKCHARACTER_TASK_LEVEL,
	emKCHARACTER_TASK_PRIMARY_FACTION,			// 主职业
	emKCHARACTER_TASK_HAT_REPRESENTID,			// 头部资源id
	emKCHARACTER_TASK_BODY_REPRESENTID,			// 身体资源id
	emKCHARACTER_TASK_LEFTWEAPON_REPRESENTID,	// 左手武器资源id
	emKCHARACTER_TASK_RIGHTWEAPON_REPRESENTID,	// 右手武器资源id
	emKCHARACTER_TASK_BACKPENDANT_REPRESENTID,	// 背部挂件id
	emKCHARACTER_TASK_HEADPENDANT_REPRESENTID,	// 头顶挂件id
	emKCHARACTER_TASK_BOTTOMPENDANT_REPRESENTID,	// 尾部挂件id
	emKCHARACTER_TASK_LEFT_SHOULDER_REPRESENTID, // 左肩
	emKCHARACTER_TASK_RIGHT_SHOULDER_REPRESENTID,// 右肩
	emKCHARACTER_TASK_RIDE_REPRESENTID,			 // 坐骑
	emKCHARACTER_TASK_PET_REPRESENTID,			//  宠物
	emKCHARACTER_TASK_ARENA_RANK_NUM,			//竞技场排名
	emKCHARACTER_TASK_CONQUER_TOWER_LAYER,		// 伐魔塔层数
	emKCHARACTER_TASK_TITLE_CARRY_1,			//正在使用的称号1
	emKCHARACTER_TASK_TITLE_CARRY_2,			//正在使用的称号2
	emKCHARACTER_TASK_TITLE_CARRY_3,			//正在使用的称号3
};
// 配置需要同步给他人（周围玩家）的变量，若修改需修改协议版本
const static WORD csWordVarSyncOther[] =
{
	emKCHARACTER_TASK_LEVEL,
	emKCHARACTER_TASK_PRIMARY_FACTION,			// 主职业
	emKCHARACTER_TASK_HAT_REPRESENTID,			// 头部资源id
	emKCHARACTER_TASK_BODY_REPRESENTID,			// 身体资源id
	emKCHARACTER_TASK_LEFTWEAPON_REPRESENTID,	// 左手武器资源id
	emKCHARACTER_TASK_RIGHTWEAPON_REPRESENTID,	// 右手武器资源id
	emKCHARACTER_TASK_BACKPENDANT_REPRESENTID,	// 背部挂件id
	emKCHARACTER_TASK_HEADPENDANT_REPRESENTID,	// 头顶挂件id
	emKCHARACTER_TASK_BOTTOMPENDANT_REPRESENTID,	// 尾部挂件id
	emKCHARACTER_TASK_LEFT_SHOULDER_REPRESENTID, // 左肩
	emKCHARACTER_TASK_RIGHT_SHOULDER_REPRESENTID,// 右肩
	emKCHARACTER_TASK_RIDE_REPRESENTID,			 // 坐骑
	emKCHARACTER_TASK_PET_REPRESENTID,			//  宠物
	emKCHARACTER_TASK_ARENA_RANK_NUM,			//竞技场排名
	emKCHARACTER_TASK_TITLE_CARRY_1,			//正在使用的称号1
	emKCHARACTER_TASK_TITLE_CARRY_2,			//正在使用的称号2
	emKCHARACTER_TASK_TITLE_CARRY_3,				//正在使用的称号3
}; 

//----------------------------存盘变量枚举不可变更，最大值255---------------------------------------
enum KE_CHARACTER_TASK_DEF_DWORD // 四字节类型 emKVARGROUP_CHARACTER_DWORD
{
	emKCHARACTER_COMMADN_FLAG,							// 普通标志位(若只占一个位的，并需存盘的变量使用这个)

	emKCHARACTER_TASK_EXP,								// 经验
	emKCHARACTER_TASK_CURRENT_LIFE,						// 当前生命值
	emKCHARACTER_TASK_CURRENT_MANA,						// 当前内力值
	emKCHARACTER_TASK_CURRENT_POWER,					// 当前力量值

	emKCHARACTER_TASK_RANK,								// 玩家水平值
	emKCHARACTER_TASK_LAST_LOGOUT_TIME,					// 上次Logout时间
	emKCHARACTER_TASK_LAST_LOGIN_TIME,					// 上次Login时间
	emCHARACTER_LAST_QUIT_TONG_TIME,                    // 上次退出家族的时间点
	emKCHARACTER_TASK_BAN_CHAT_END_TIME,				// 禁言持续到何时UTC
	emKCHARACTER_TASK_EXT_BAG,							// 扩展背包 add by NiuNiu
	emKCHARACTER_TASK_LAST_UPDATE_ESCORT_TIME,			// 玩家上一次更新修仙的时间(LogicFrame);
	emKCHARACTER_TASK_CUR_ESCORT_TASK_ID,				// 当前刷新的修仙任务ID
	emKCHARACTER_TASK_RECEIVED_ESCORT_TASK_ID,			// 已接修仙任务的ID
	emKCHARACTER_TASK_LAST_UPDATE_BOWL_FREE_TIME,		//聚宝盆上一次免费获取的时间
	emKCHARACTER_TASK_BOWL_FREE_CUMULATIVE_TIME,		//聚宝盆免费领取累计时间
	emKCHARACTER_TASK_ESCORT_AWARD_TOTAL_EXP,			//每日修仙获得的总经验值
	emKCHARACTER_TASK_ESCORT_AWARD_TOTAL_ENERGY,		//每日修仙获得的总真气值
	emKCHARACTER_TASK_LAST_TEAM_MSG_TIME,						// 上次创建队伍群发的时间
	emKCHARACTER_TASK_CHANGE_NAME_COLOR,			//名字变色
	emKCHARACTER_TASK_DWORD_SAVED_END,					// 存盘变量结束ID	

	// UnSaved，以下非存盘变量枚举可变更，但要同步修改脚本

	emKCHARACTER_TASK_MAX_LIFE,							// 最大生命值
 	emKCHARACTER_TASK_MAX_MANA,							// 最大内力值
	emKCHARACTER_TASK_MAX_POWER,						// 最大力量值

	emKCHARACTER_TASK_ATTACK_ABILITY,					// 攻击
	emKCHARACTER_TASK_HITCOEFFICIENT,					// 命中系数
	emKCHARACTER_TASK_DODGE_ABILITY,						// 闪避
	emKCHARACTER_TASK_DEF_ABILITY,					// 防御
	emKCHARACTER_TASK_SPEED_ABILITY,					// 移动速度
	emKCHARACTER_TASK_SPEEDDELAYSET,                   // 将要设置移动的速度(下次移动)

	emKCHARACTER_TASK_CRITICAL_VALUE,					// 会心值
	emKCHARACTER_TASK_CRITICAL_ABILITY,					// 会心伤害
	emKCHARACTER_TASK_RESIST,			// 抵御会心率
	emKCHARACTER_TASK_CRITICAL_DEABILITY,				// 抵御会心伤害

	emKCHARACTER_TASK_IGNORE_DEF,                       // 破防概率

	emKCHARACTER_TASK_CURING_LIFE_BASE,					// 治疗生命基础值
	emKCHARACTER_TASK_CURING_LIFE,						// 治疗生命值
	emKCHARACTER_TASK_CURING_MANA_BASE,					// 治疗内力基础值
	emKCHARACTER_TASK_CURING_MANA,						// 治疗内力值

	emKCHARACTER_TASK_WITHSTAND_NORMAL_P,				// 普通抵挡伤害百分比[0~100]
	emKCHARACTER_TASK_WITHSTAND_NORMAL_V,				// 普通抵挡伤害值
	emKCHARACTER_TASK_REBOUND_P,						// 反弹伤害概率属性
	emKCHARACTER_TASK_REBOUND_V,						// 反弹伤害值
	emKCHARACTER_TASK_TRANSTOLIFE_P,					// 伤害转生命[0~100]
	emKCHARACTER_TASK_TRANSTOMANA_P,					// 伤害转魔法[0~100]
	emKCHARACTER_TASK_ENLARGE_ATTACK_P,					// 放大伤害百分比[0~100]
	emKCHARACTER_TASK_REDUCE_ATTACK_P,					// 减少伤害百分比

 	emKCHARACTER_TASK_TEAM_ID,										// 队伍ID，需要同步给周边玩家，所以不能放在playerdef.h中
 	emKCHARACTER_TASK_FOLLOW_TARGET,                            // 跟随目标，自己身前的
 	emKCHARACTER_TASK_FOLLOWED_BY,                              // 直接跟随者，自己身后的
 	emKCHARACTER_TASK_AI_TYPE,									// AI类型
	emKCHARACTER_TASK_RELATION,
	emKCHARACTER_TASK_CURRENT_DAMAGE,                           // 当前伤害值
	emKCHARACTER_TASK_MODIFYDMG_P,								// 伤害加成
	emKCHARACTER_TASK_MEDICINE_EFFECT,							// 药效

	emKCHARACTER_TASK_ENABLE_ENYMY_CONDITION,			// 活动中是否使用敌人判断条件
	emKCHARACTER_TASK_ENYMY_CONDITION1,					// 活动分组条件，用来确定活动中是否敌对关系
	emKCHARACTER_TASK_ENYMY_CONDITION2,
	emKCHARACTER_TASK_ENYMY_CONDITION3,
	emKCHARACTER_TASK_ENYMY_CONDITION4,
	emKCHARACTER_TASK_ENYMY_CONDITION5,

	emKCHARACTER_TASK_FIGHT_SCORE,						// 角色战斗力评分
	emKCHARACTER_TASK_OVERALL_TEAM_IDX,				// 当前所在队伍索引

	emKCHARACTER_TASK_ANGER_LEFT_TIME,				// 大神形态剩余时间

	emKCHARACTER_TASK_MULTI_MAP_ID,					// 当前副本队伍地图id

	emKCHARACTER_TASK_LAST_TAKE_MAKEUP_TIME,		// 上次领补偿时间

	emKCHARACTER_TASK_DTASK1,		                // 日常任务1
	emKCHARACTER_TASK_DTASK2,		                // 日常任务2
	emKCHARACTER_TASK_DTASK3,		                // 日常任务3
	emKCHARACTER_TASK_DTASK4,		                // 日常任务4
	emKCHARACTER_TASK_DTASK_REFRESH_TIME,           // 日常任务刷新时间
	emKCHARACTER_TASK_DTASK_TIMES_REFRESH_TIME,     // 日常任务次数刷新时间
	emKCHARACTER_TASK_DTASK_USED_TIMES,             // 日常任务使用次数


	emKCHARACTER_TASK_TINY_TERMINAL,                // 是否是微端登录
	
	emKCHARACTER_TASK_DWORD_MAX // 枚举数
};
// 配置需要同步给自己的变量，若修改需修改协议版本
const static WORD csDWordVarSyncSelf[] =
{
	emKCHARACTER_TASK_LAST_LOGOUT_TIME,					// 上次Logout时间
	emKCHARACTER_TASK_EXP,								// 经验
	emKCHARACTER_TASK_CURRENT_LIFE,						// 当前生命值
	emKCHARACTER_TASK_CURRENT_MANA,						// 当前内力值
	emKCHARACTER_TASK_CURRENT_POWER,					// 当前力量值

	emKCHARACTER_TASK_MAX_LIFE,							// 最大生命值
 	emKCHARACTER_TASK_MAX_MANA,							// 最大内力值
	emKCHARACTER_TASK_MAX_POWER,						// 最大力量值

	emKCHARACTER_TASK_ATTACK_ABILITY,					// 攻击
	emKCHARACTER_TASK_HITCOEFFICIENT,					// 命中值
	emKCHARACTER_TASK_DODGE_ABILITY,
	emKCHARACTER_TASK_DEF_ABILITY,					// 防御
	emKCHARACTER_TASK_SPEED_ABILITY,					// 移动速度
	emKCHARACTER_TASK_SPEEDDELAYSET,                   // 将要设置移动的速度(下次移动)

	emKCHARACTER_TASK_CRITICAL_VALUE,					// 会心值
	emKCHARACTER_TASK_CRITICAL_ABILITY,					// 会心伤害
	emKCHARACTER_TASK_IGNORE_DEF,

	emKCHARACTER_TASK_RESIST,

	emKCHARACTER_TASK_CURING_LIFE,						// 治疗生命值
	emKCHARACTER_TASK_CURRENT_DAMAGE,                   // 当前伤害值
	emKCHARACTER_TASK_MODIFYDMG_P,						// 伤害加成
	emKCHARACTER_TASK_EXT_BAG,							// 扩展背包
	emKCHARACTER_TASK_LAST_UPDATE_ESCORT_TIME,			// 上一次更新修仙任务的时间
	emKCHARACTER_TASK_CUR_ESCORT_TASK_ID,				// 当前刷新的修仙任务ID
	emKCHARACTER_TASK_RECEIVED_ESCORT_TASK_ID,			// 已接修仙任务的ID
	emKCHARACTER_TASK_ESCORT_AWARD_TOTAL_EXP,			// 每日修仙获得的总经验值
	emKCHARACTER_TASK_ESCORT_AWARD_TOTAL_ENERGY,		// 每日修仙获得的总真气值
	emKCHARACTER_TASK_LAST_UPDATE_BOWL_FREE_TIME,		//聚宝盆上一次免费获取的时间
	emKCHARACTER_TASK_BOWL_FREE_CUMULATIVE_TIME,		//聚宝盆免费领取累计时间
	emCHARACTER_LAST_QUIT_TONG_TIME,                    // 上次退出家族的时间点
	emKCHARACTER_TASK_CHANGE_NAME_COLOR,			    //名字变色

	emKCHARACTER_TASK_TEAM_ID,

	emKCHARACTER_TASK_ENABLE_ENYMY_CONDITION,			// 活动中是否使用敌人判断条件
	emKCHARACTER_TASK_ENYMY_CONDITION1,
	emKCHARACTER_TASK_ENYMY_CONDITION2,
	emKCHARACTER_TASK_ENYMY_CONDITION3,
	emKCHARACTER_TASK_ENYMY_CONDITION4,
	emKCHARACTER_TASK_ENYMY_CONDITION5,

	emKCHARACTER_TASK_FIGHT_SCORE,
	emKCHARACTER_TASK_LAST_TEAM_MSG_TIME,
	emKCHARACTER_TASK_OVERALL_TEAM_IDX,
	emKCHARACTER_TASK_ANGER_LEFT_TIME,
	emKCHARACTER_TASK_MULTI_MAP_ID,
	emKCHARACTER_TASK_TINY_TERMINAL,                    // 是否是微端登录
};

// 配置需要同步给他人（周围玩家）的变量，若修改需修改协议版本
const static WORD csDWordVarSyncOther[] =
{
	emKCHARACTER_TASK_CURRENT_LIFE,						// 当前生命值
	emKCHARACTER_TASK_CURRENT_MANA,						// 当前内力值
	emKCHARACTER_TASK_CURRENT_POWER,					// 当前力量值

	emKCHARACTER_TASK_MAX_LIFE,							// 最大生命值
 	emKCHARACTER_TASK_MAX_MANA,							// 最大内力值
	emKCHARACTER_TASK_MAX_POWER,						// 最大力量值

	emKCHARACTER_TASK_ATTACK_ABILITY,					// 攻击
	emKCHARACTER_TASK_HITCOEFFICIENT,					// 命中值
	emKCHARACTER_TASK_DODGE_ABILITY,						// 闪避
	emKCHARACTER_TASK_DEF_ABILITY,					// 防御
	emKCHARACTER_TASK_SPEED_ABILITY,					// 移动速度

	emKCHARACTER_TASK_CRITICAL_VALUE,					// 会心值
	emKCHARACTER_TASK_CRITICAL_ABILITY,					// 会心伤害
	emKCHARACTER_TASK_RESIST,

	emKCHARACTER_TASK_CURING_LIFE,						// 治疗生命值

	emKCHARACTER_TASK_FIGHT_SCORE,

	emKCHARACTER_TASK_RECEIVED_ESCORT_TASK_ID,				//当前已接修仙任务ID
	emKCHARACTER_TASK_CHANGE_NAME_COLOR,			//名字变色

	emKCHARACTER_TASK_ENABLE_ENYMY_CONDITION,			// 活动中是否使用敌人判断条件
	emKCHARACTER_TASK_ENYMY_CONDITION1,
	emKCHARACTER_TASK_ENYMY_CONDITION2,
	emKCHARACTER_TASK_ENYMY_CONDITION3,
	emKCHARACTER_TASK_ENYMY_CONDITION4,
	emKCHARACTER_TASK_ENYMY_CONDITION5,

	emKCHARACTER_TASK_ANGER_LEFT_TIME,


	emKCHARACTER_TASK_TINY_TERMINAL,                // 是否是微端登录
};

//----------------------------存盘变量枚举不可变更，最大值255---------------------------------------
enum KE_CHARACTER_TASK_DEF_MAP // Map动态类型 emKVARGROUP_CHARACTER_MAP，值 != 0 时才会占用空间
{
	// Add By ZZ, 聊天喇叭，需要存盘
	emKCHARACTER_CHAT_WORLD_SPEAKER,							// 线聊喇叭
	emKCHARACTER_CHAT_WORLD_FREESPEAKER,						// 赠送的线聊喇叭
	emKCHARACTER_CHAT_WORLD_FREESPEAKER_RESETTIME,				// 上一次线聊喇叭赠送时间
	emKCHARACTER_CHAT_GLOBAL_SPEAKER,							// 全区喇叭
	// End
	emCHARACTER_FACTION_BATTLE_RANK,                            // 门派竞技排名
	emCHARACTER_GLOBAL_BATTLE_SCORE,                            // 跨服战场积分
	emKCHARACTER_TASK_MAP_SAVED_END,							// 存盘变量结束ID

	// UnSaved，以下非存盘变量枚举可变更，但要同步修改脚本
	emCHARACTER_LEVEL_DIFFICUTY,                                // 关卡难度
	emKCHARACTER_TASK_MAP_MAX // 枚举数
};

// 配置需要同步给自己的变量，若修改需修改协议版本
const static WORD csMapVarSyncSelf[] =
{
	emKCHARACTER_CHAT_WORLD_SPEAKER,
	emKCHARACTER_CHAT_WORLD_FREESPEAKER,
	emKCHARACTER_CHAT_WORLD_FREESPEAKER_RESETTIME,
	emKCHARACTER_CHAT_GLOBAL_SPEAKER,
	emCHARACTER_FACTION_BATTLE_RANK,                            // 门派竞技排名
	emCHARACTER_GLOBAL_BATTLE_SCORE,                            // 跨服战场积分
};
// 配置需要同步给他人（周围玩家）的变量，若修改需修改协议版本
const static WORD csMapVarSyncOther[] =
{
	emKCHARACTER_CHAT_GLOBAL_SPEAKER // 随便增加的，以免编译器报错（zzx）
};

// 标志位定义，最大值32
enum KE_CHARACTER_COMMON_FLAG
{

};

enum KE_CHARACTER_CTRL_ID
{
	emKCHARACTER_CTRL_SKILL,
	emCHARACTER_CTRL_BUFFER,  // 游龙buffer
	emCHARACTER_CTRL_FACTION, // 游龙玩家门派
	emKCHARACTER_CTRL_FIGHTSKILL,  // 技能控制

	emKCHARACTER_CTRL_AI_DATA,		// AI模块
	emCHARACTER_CTRL_AI_VM,		// AI模块
	emCHARACTER_CTRL_THREAT_LIST,

	emKCHARACTER_CTRL_PLAYER_BEGIN, // Player特有的Ctrl

	emKCHARACTER_CTRL_PLAYER_ITEM = emKCHARACTER_CTRL_PLAYER_BEGIN, // 玩家物品
	emKCHARACTER_CTRL_PLAYER_RECIPE,	// 玩家配方
	emKCHARACTER_CTRL_PLAYER_PK,		// 玩家PK管理
	emKCHARACTER_CTRL_TASK,				// 玩家任务处理	
	emKCHARACTER_CTRL_PLAYER_PURSE,		// 玩家钱袋
	emKCHARACTER_CTRL_PLAYER_CHAT,
	emKCHARACTER_CTRL_PLAYER_FINDPATH,  // 寻路

	emKCHARACTER_CTRL_PLAYER_MAIL,		// 邮件
	emKCHARACTER_CTRL_PLAYER_PROGRESS_BAR, // 进度条
	emPLAYER_CTRL_TEAM,
	emKCHARACTER_CTRL_PLAYER_PET,					// 宠物
	emKCHARACTER_CTRL_PLAYER_RIDE,					// 坐骑
	emKCHARACTER_CTRL_PLAYER_QUIZ,				// 问卷处理 kk
	emKCHARACTER_CTRL_PLAYER_ARENA,				// PVE竞技场

	emKCHARACTER_CTRL_PLAYER_AWARD,

	emKCHARACTER_CTRL_PLAYER_TOWER,			// 伐魔塔
	emKCHARACTER_CTRL_PLAYER_STAGE,			// 关卡
	emKCHARACTER_CTRL_PLAYER_MEDITATION,	//打坐

	emKCHARACTER_CTRL_PLAYER_TITLE,			//称号

	emKCHARACTER_CTRL_PLAYER_INSTANCE,		// 副本
	emKCHARACTER_CTRL_PLAYER_ACTIVITY,			// 活动
	emKCHARACTER_CTRL_PLAYER_RANK,			// 排行榜
	emKCHARACTER_CTRL_TARGET,		//目标
	emKCHARACTER_CTRL_VIP,		//vip
	emKCHARACTER_CTRL_AWARD_LOBBY,		//

	emKCHARACTER_CTRL_PLAYER_BLADE,		// 变身

	emKCHARACTER_CTRL_GEM,		//宝石

	emKCHARACTER_CTRL_CROSS_SV,		// 跨服相关

	emKCHARACTER_CTRL_ARTIFACT,		//神器

	emKCHARACTER_CTRL_PLAYER_ESCORT,	// 修仙

	emKCHARACTER_CTRL_PLAYER_BANK,	//银行

	emKCHARACTER_CTRL_SHOP,	//商城

	emKCHARACTER_CTRL_OPENSE, //开服活动

	emKCHARACTER_CTRL_NPC_BEGIN, // Npc特有的Ctrl

	emKCHARACTER_CTRL_MAX,
};

// 阵营，若camp1和camp2有覆盖关系A>B ? (A-B) == (A^B) : (B-A) == (A^B)则属于友善阵营，否则是敌对阵营
enum KE_CHARACTER_CAMP
{
	emKCHARACTER_CAMP_BLACK		= 0,
	emKCHARACTER_CAMP_RED		= 1,	// r
	emKCHARACTER_CAMP_GREEN		= 2,	// g
	emKCHARACTER_CAMP_BLUE		= 4,	// b

	emKCHARACTER_CAMP_YELLOW	= 3,	// rg
	emKCHARACTER_CAMP_MAGENTA	= 5,	// rb	
	emKCHARACTER_CAMP_CYAN		= 6,	// gb

	emKCHARACTER_CAMP_WHITE		= 7,	// rgb
};

enum KE_CHARACTER_PROPERTY
{
	emKCHARACTER_PROPERTY_NONE = 0,    
	emKCHARACTER_PROPERTY_WIND,            // 风
	emKCHARACTER_PROPERTY_THUNDER,         // 雷
	emKCHARACTER_PROPERTY_WATER,		   // 水
	emKCHARACTER_PROPERTY_FIRE,			   // 火
	emKCHARACTER_PROPERTY_COUNT,           // end
};
// -------------------------------------------------------------------------
