# Generated by vc2mak. (c) 2012 simon<senoutouya@gmail.com>.
# Project - coordinator

# 缺省配置
ifndef CFG
	CFG=debug
endif

# 编译器标记（若要做x86、x64的cross-compile请指定PLAT参数）
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
CFLAGS = -pthread $(PLAT)
LDFLAGS:=$(CFLAGS)
PLATLIBS += -lm -ldl -lrt $(PLATLIB)
endif

ifeq ($(UNAME), Solaris)
CFLAGS = -pthreads -I/usr/local/include $(PLAT)
LDFLAGS:=$(CFLAGS) -L/usr/local/lib
PLATLIBS += -lz -liconv -lm -lrt $(PLATLIB)
endif

ifeq ($(UNAME), FreeBSD)
CFLAGS = -pthread -I/usr/local/include $(PLAT)
LDFLAGS:=$(CFLAGS) -L/usr/local/lib
PLATLIBS += -lz -liconv -lm -lrt $(PLATLIB)
endif

CC=gcc
CXX=g++
CXXFLAGS=$(CFLAGS)
LD=$(CXX)
AR=ar
ARFLAGS=rcs

# 工程配置表
ifeq "$(CFG)" "debug"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O0 -fexceptions -g -fstack-protector  -D_DEBUG -D_CONSOLE -DGAME_CENTER -I. -I../../include -I../../include/serverbase -I../../../LibQrt/Include -I/usr/include/mysql
	LDFLAGS+= -L../../lib/debug -L../../../LibQrt/Lib/ -L../../../devenv/lib/debug -L/usr/lib64/mysql -L../../product/
	LIBS=-Wl,-rpath,'$$ORIGIN' -Wl,--start-group -lcoreD -lyol_libd -lmysqlclient ../../../3rd/lua-5.1.4/src/liblua.a -Wl,--end-group $(PLATLIBS)
	TARGET=../../product/coordinatord.elf
	VC_CONF_TYPE=typeApplication
endif

ifeq "$(CFG)" "release"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O2 -fexceptions -g -fstack-protector  -DNDEBUG -D_CONSOLE -I. -I../../include -I../../include/serverbase -I../../../base/include -I/usr/include/mysql
	LDFLAGS+= -L../../lib/release -L../../../base/lib/release -L../../../devenv/lib/release -L/usr/lib64/mysql
	LIBS=-Wl,-rpath,'$$ORIGIN' -Wl,--start-group -lengine -lcommon -Wl,--end-group $(PLATLIBS)
	TARGET=../../product/release/coordinator/coordinator.elf
	VC_CONF_TYPE=typeApplication
endif

.PHONY: all
all: $(TARGET)

ifndef TARGET
	@echo "无编译目标！unrecognized \$$CFG '$(CFG)'"
	@exit 1
endif

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cxx
	$(CXX) $(CXXFLAGS) -o $@ -c $<

DATABASE= \
	./DBBase.cpp \
	./DBBase.h \
	./dbmanager.cpp \
	./dbmanager.h \
	./DBTools.cpp \
	./DBTools.h \
	./IDSequence.cpp \
	./IDSequence.h \
	./MiscDB.cpp \
	./MiscDB.h \
	./MiscDBThread.cpp \
	./RoleDB.cpp \
	./RoleDB.h \
	./GMSendAwardDB.cpp \
	./GMSendAwardDB.h \
	./openseSave.cpp \
	./openseSave.h \
	./RoleDBThread.cpp \
	./StatDataManager.cpp \
	./StatDataManager.h 

FRAMEWORK= \
	./coordinator.cpp \
	./GameCenter.cpp \
	./GameCenter.h \
	./GameCenterSettings.cpp \
	./GameCenterSettings.h \
	./gclogicbasescript.cpp \
	./gcplayercommon.cpp \
	./KRole.cpp \
	./KRole.h \
	./RoleManager.cpp \
	./RoleManager.h \
	./stdafx.cpp \
	./stdafx.h 

跨服战区= \
	./battlezone/battlezone.cpp \
	./battlezone/battlezone.h \
	./battlezone/battlezonedef.h \
	./battlezone/battlezonemaster.cpp \
	./battlezone/battlezonemaster.h \
	./battlezone/battlezoneslave.cpp \
	./battlezone/battlezoneslave.h 

队伍= \
	./team/TeamCenter.cpp \
	./team/TeamCenter.h \
	./team/teammodule_gc.cpp \
	./team/teammodule_gc.h 

GLOBALDATA= \
	./globaldata/GlobalDataDbProcess.cpp \
	./globaldata/GlobalDataDbProcess.h \
	./globaldata/GlobalDataModule.cpp \
	./globaldata/GlobalDataModule.h \
	./globaldata/GlobalDataProtocolProcess.cpp \
	./globaldata/GlobalDataProtocolProcess.h \
	./globaldata/GlobalDataScript.cpp \
	./globaldata/ScheduleTaskCenter.cpp \
	./globaldata/ScheduleTaskCenter.h 

NETWORK= \
	./GameCenterMonitor.cpp \
	./GameCenterMonitor.h \
	./GatewayAgency.cpp \
	./GatewayAgency.h \
	./LogServerAgency.cpp \
	./LogServerAgency.h \
	./PayAgency.cpp \
	./PayAgency.h \
	./ServerHandler.cpp \
	./ServerHandler.h 

MAP= \
	./BornPlaceList.cpp \
	./BornPlaceList.h \
	./MapCopy.cpp \
	./MapCopy.h \
	./MapInfo.cpp \
	./MapInfo.h \
	./MapManager.cpp \
	./MapManager.h 

KIN= \
	./kin/Kin.cpp \
	./kin/Kin.h \
	./kin/kinhandler.cpp \
	./kin/kinhandler.h \
	./kin/KinHistory.cpp \
	./kin/KinHistory.h \
	./kin/KinManager.cpp \
	./kin/KinManager.h \
	./kin/KinRepertory.cpp \
	./kin/KinRepertory.h \
	./KinScript.cpp 

邮件= \
	./mail2/MailBox.cpp \
	./mail2/MailBox.h \
	./mail2/MailChecker.cpp \
	./mail2/MailChecker.h \
	./mail2/MailManager.cpp \
	./mail2/MailManager.h \
	./mail2/MailOperation.h \
	./mail2/MailServerHandler.cpp 

RELATION= \
	./relation/bidequalrelationfactory_t.h \
	./relation/bidfriendrelation.cpp \
	./relation/bidfriendrelation.h \
	./relation/bidunequalrelationfactory_t.h \
	./relation/buddyfactory.cpp \
	./relation/buddyfactory.h \
	./relation/closefriendrelation.cpp \
	./relation/closefriendrelation.h \
	./relation/couplefactory.cpp \
	./relation/couplefactory.h \
	./relation/datarelation_t.h \
	./relation/enemyfactory.cpp \
	./relation/enemyfactory.h \
	./relation/friendfactory.cpp \
	./relation/friendfactory.h \
	./relation/introductionfactory.cpp \
	./relation/introductionfactory.h \
	./relation/playerrelation_datadef.h \
	./relation/playerrelation_i.h \
	./relation/relation.cpp \
	./relation/relation.h \
	./relation/relationcounter.cpp \
	./relation/relationcounter.h \
	./relation/relationfactorylist.cpp \
	./relation/relationfactorylist.h \
	./relation/relationmanager.cpp \
	./relation/relationmanager.h \
	./relation/relationrulemanager.cpp \
	./relation/relationrulemanager.h \
	./relation/tmpfriendfactory.cpp \
	./relation/tmpfriendfactory.h \
	./relation/trainingfactory.cpp \
	./relation/trainingfactory.h \
	./relation/trainingsetting.cpp \
	./relation/trainingsetting.h \
	./relation/unirelationfactory.cpp \
	./relation/unirelationfactory.h 

RELATION.SCRIPT= \
	./relation/relationscriptfuns.cpp \
	./relation/relationscriptfuns_table.hpp 

RELATION.LOADSAVE= \
	./relation/datasaveloader.cpp \
	./relation/datasaveloader.h 

拍卖行= \
	./auction/AuctionManager.cpp \
	./auction/AuctionManager.h \
	./auction/AuctionOperation.h \
	./auction/AuctionServerHandler.cpp 

GLOBALSERVER= \
	./globalservermaster.cpp \
	./globalservermaster.h \
	./globalserverprotocolhandler.h \
	./globalserverslave.cpp \
	./globalserverslave.h 

ARENAPVE竞技场= \
	./arena/ArenaManager.cpp \
	./arena/ArenaManager.h \
	./arena/ArenaServerHandler.cpp \
	./arena/ArenaServerHandler.h 

RANK= \
	./rank/krankhandler.cpp \
	./rank/krankhandler.h \
	./rank/krankmanager.cpp \
	./rank/krankmanager.h \
	./rank/krankpool.cpp \
	./rank/krankpool.h 

QRANDOMNAME随机名字= \
	./QRandomName/QRandomName.cpp \
	./QRandomName/QRandomName.h 

QUIZ= \
	./quiz/QuizManager.cpp \
	./quiz/QuizManager.h \
	./quiz/QuizServerHandler.cpp \
	./quiz/QuizServerHandler.h 

RECORD= \
	./record/krecordmanager.cpp \
	./record/krecordmanager.h \
	./record/krecordserverhandler.cpp \
	./record/krecordserverhandler.h \
	./record/recorddef.h 

跨服排队= \
	./overallqueue/kqueuedef.h \
	./overallqueue/kqueuehandler.cpp \
	./overallqueue/kqueuehandler.h \
	./overallqueue/kqueuemaster.cpp \
	./overallqueue/kqueuemaster.h \
	./overallqueue/kqueueslave.cpp \
	./overallqueue/kqueueslave.h 

修仙= \
	../../include/onlinegamemodule/kescortdef.h \
	./escort/kescorthandler.cpp \
	./escort/kescorthandler.h \
	./escort/kescortmanager.cpp \
	./escort/kescortmanager.h 

SRCS=$(DATABASE) $(FRAMEWORK) $(跨服战区) $(队伍) $(GLOBALDATA) $(NETWORK) $(MAP) $(KIN) $(邮件) $(RELATION) $(RELATION.SCRIPT) $(RELATION.LOADSAVE) $(拍卖行) $(GLOBALSERVER) $(ARENAPVE竞技场) $(RANK) $(QRANDOMNAME随机名字) $(QUIZ) $(RECORD) $(跨服排队) $(修仙) 

OBJS=$(patsubst %.cxx,%.o,$(patsubst %.cpp,%.o,$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(filter %.c %.cc %.cpp %.cxx,$(SRCS))))))

ifeq "$(VC_CONF_TYPE)" "typeApplication"
$(TARGET): $(OBJS)
	mkdir -p "$(dir $(TARGET))"
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
endif

.PHONY: clean
clean:
	-rm -f $(OBJS) coordinator.dep  ../../product/coordinatord.elf

.PHONY: depends
depends:
	-$(CXX) $(CXXFLAGS) -MM $(filter %.c %.cc %.cpp %.cxx,$(SRCS)) > coordinator.dep

-include coordinator.dep

