# Generated by vc2mak. (c) 2012 simon<senoutouya@gmail.com>.
# Project - QMysqlDB

# 缺省配置
ifndef CFG
	CFG=Debug
endif

# 编译器标记（若要做x86、x64的cross-compile请指定PLAT参数）
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
PLAT += -pthread
PLATLIBS += -lm -ldl -lrt
endif

ifeq ($(UNAME), Solaris)
PLAT += -pthreads
PLATLIBS += -L/usr/local/lib -lz -liconv -lm -lrt
endif

ifeq ($(UNAME), FreeBSD)
PLAT += -pthread -I/usr/local/include
PLATLIBS += -L/usr/local/lib -lz -liconv -lm -lrt
endif

CC=gcc
CFLAGS=$(PLAT)
CXX=g++
CXXFLAGS=$(CFLAGS)
LD=$(CXX)
LDFLAGS:=$(CFLAGS)
AR=ar
ARFLAGS=rcs

# 工程配置表
ifeq "$(CFG)" "Debug"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O0 -fexceptions -g -fstack-protector  -D_DEBUG  -I../../Include -I/usr/include/mysql
	TARGET=Debug/libQMysqlD.a
	VC_CONF_TYPE=typeStaticLibrary
endif

ifeq "$(CFG)" "Release"
	CFLAGS+= -pipe -Wall -Wno-unknown-pragmas -Wno-unused -Wno-reorder -O2 -fexceptions -g -fstack-protector  -DNDEBUG  -I../../../Include -I/usr/include/mysql
	TARGET=Release/libQMysql.a
	VC_CONF_TYPE=typeStaticLibrary
endif

.PHONY: all
all: $(TARGET)

ifndef TARGET
	@echo "无编译目标！unrecognized \$$CFG '$(CFG)'"
	@exit 1
endif

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<
%.o: %.cxx
	$(CXX) $(CXXFLAGS) -o $@ -c $<

QMYSQL.VCPROJ= \
	./KGD_Local.rc \
	./stdafx.h 

SOURCE_FILES= \
	./KGD_Connect.cpp \
	./KGD_Error.cpp \
	./KGD_MySQL_Database.cpp \
	./KGD_MySQL_Field.cpp \
	./KGD_MySQL_Result.cpp \
	./stdafx.cpp 

HEADER_FILES= \
	../../Include/Misc/IDatabase.h \
	./KGD_Error.h \
	./KGD_MySQL_Database.h \
	./KGD_MySQL_Field.h \
	./KGD_MySQL_Result.h \
	./KGD_Name.h 

SRCS=$(QMYSQL.VCPROJ) $(SOURCE_FILES) $(HEADER_FILES) 

OBJS=$(patsubst %.cxx,%.o,$(patsubst %.cpp,%.o,$(patsubst %.cc,%.o,$(patsubst %.c,%.o,$(filter %.c %.cc %.cpp %.cxx,$(SRCS))))))

ifeq "$(VC_CONF_TYPE)" "typeStaticLibrary"
$(TARGET): $(OBJS)
	mkdir -p "$(dir $(TARGET))"
	$(AR) $(ARFLAGS) $@ $(OBJS)
endif

.PHONY: clean
clean:
	-rm -f $(OBJS) QMysqlDB.dep  Debug/libQMysqlD.a Release/libQMysql.a

.PHONY: depends
depends:
	-$(CXX) $(CXXFLAGS) -MM $(filter %.c %.cc %.cpp %.cxx,$(SRCS)) > QMysqlDB.dep

-include QMysqlDB.dep

