

#include "stdafx.h"
#include "onlinegamemodule/kteamprotocol.h"
#include "kteammodule.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// -------------------------------------------------------------------------
BOOL QTeamModule::InitProtocol()
{
	// C2S
	KD_PTC_FIXED_SIZE_C2S(C2S_INVITE_JOIN_TEAM_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_INVITE_JOIN_TEAM_RESPOND);
	KD_PTC_FIXED_SIZE_C2S(C2S_APPLY_JOIN_TEAM_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_APPLY_JOIN_TEAM_RESPOND);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_DEL_MEMBER_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_CHANGE_AUTHORITY_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_SET_LOOT_MODE_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_SET_ROLL_QUALITY_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_SET_FORMATION_LEADER_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_MEMBER_NOTIFY_SIGNPOST_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_SET_MARK_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_LEVEL_UP_RAID_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_TEAM_CHANGE_MEMBER_GROUP_REQUEST);

	KD_PTC_FIXED_SIZE_C2S(C2S_CREATE_TEAM_REQUEST);
	KD_PTC_FIXED_SIZE_C2S(C2S_DISBAND_TEAM_REQUEST);
	
	// S2C
	KD_PTC_LENGTNED_SIZE_S2C(S2C_SYNC_PLAYER_TEAM_BASE_INFO);
	KD_PTC_FIXED_SIZE_S2C(S2C_INVITE_JOIN_TEAM_REQUEST);
	KD_PTC_FIXED_SIZE_S2C(S2C_APPLY_JOIN_TEAM_REQUEST);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_ADD_MEMBER_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_DEL_MEMBER_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_CHANGE_AUTHORITY_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_SET_LOOT_MODE_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_SET_FORMATION_LEADER_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_DISBAND_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_SYNC_TEAM_MEMBER_ONLINE_FLAG);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_MEMBER_SIGNPOST_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_SET_MARK_RESPOND);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_CAMP_CHANGE);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_LEVEL_UP_RAID_NOTIFY);
	KD_PTC_FIXED_SIZE_S2C(S2C_TEAM_CHANGE_MEMBER_GROUP_NOTIFY);

	KD_PTC_FIXED_SIZE_S2C(S2C_SYNC_TEAM_MEMBER_MAX_LMR);
	KD_PTC_FIXED_SIZE_S2C(S2C_SYNC_TEAM_MEMBER_CURRENT_LMR);
	KD_PTC_FIXED_SIZE_S2C(S2C_SYNC_TEAM_MEMBER_MISC);
	KD_PTC_FIXED_SIZE_S2C(S2C_SYNC_TEAM_MEMBER_POSITION);
	
	return TRUE;
}
// -------------------------------------------------------------------------
